# Modelling a repurchase agreement (repo) and handling instrument events

This notebook demonstrates the concepts described in the following KBs:

* Mastering a `FlexibleRepo` instrument, establishing a position, and performing a valuation: https://support.lusid.com/docs/modelling-repurchase-agreements-in-lusid
* Handling instrument events: https://support.lusid.com/docs/handling-instrument-events-for-repurchase-agreements

Two `FlexibleRepo` instruments are created, with separate positions in two portfolios. The two instruments are identical except one is a `Buyer` and the other a `Seller`:

* Both are `TermRepo` by default but the code for `OpenRepo` is present and commented out.
* Underlying is a simple fixed-rate `Bond` with monthly coupon payments.
* Transaction date: 01 Jan 2025 (Note the 'purchase' transaction of a `FlexibleRepo` **must be before** the instrument start date)
* Instrument start date: 02 Jan 2025
* Maturity date: 31 Mar 2025
* Random valuation date: 15 Feb 2025
* Accrual basis: Act 365
* Collateral value: £1,100,000
* Purchase price: £1,000,000
* Margin: 1.1
* Haircut: 0.091
* Repurchase price: £1,012,054.79
* Repo rate : 5%

## Setup

In [1]:
import os
import pandas as pd
import json
import uuid
from IPython.core.display import HTML
import logging
from datetime import datetime, timezone, timedelta
logging.basicConfig(level = logging.INFO)

import finbourne.sdk.services.lusid.api as la
import finbourne.sdk.services.lusid.models as lm

from finbourne.sdk.extensions import SyncApiClientFactory, RefreshingToken
from finbourne.sdk.exceptions import ApiException
from finbourne_sdk_utils.pandas_utils.lusid_pandas import lusid_response_to_data_frame
from finbourne_sdk_utils.lpt.lpt import to_date

# Set pandas display options
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.options.display.float_format = "{:,.2f}".format

# Authenticate to SDK
# Run the Notebook in Jupyterhub for your LUSID domain and authenticate automatically
secrets_path = os.getenv("FBN_SECRETS_PATH")
# Run the Notebook locally using a secrets file (see https://support.lusid.com/docs/how-do-i-use-an-api-access-token-with-the-lusid-sdk)
if secrets_path is None:
    secrets_path = os.path.join(os.path.dirname(os.getcwd()), "secrets.json")

# Initiate an API Factory which is the client side object for interacting with LUSID APIs
api_factory = SyncApiClientFactory(
    access_token=RefreshingToken(),
    secrets_path=secrets_path,
    app_name="LusidJupyterNotebook"
)
    
# Confirm success by printing SDK version
api_status = pd.DataFrame(api_factory.build(la.ApplicationMetadataApi).get_lusid_versions().to_dict())
display(api_status)

,apiVersion,buildVersion,excelVersion,links
0,v0,0.6.15978.0,0.5.3666,"{'relation': 'RequestLogs', 'href': 'https://j..."

In [2]:
# Build all the required APIs
try:
    instruments_api = api_factory.build(la.InstrumentsApi)
    instrument_events_api = api_factory.build(la.InstrumentEventsApi)
    instrument_event_type_api = api_factory.build(la.InstrumentEventTypesApi)
    aggregation_api = api_factory.build(la.AggregationApi)
    recipe_api = api_factory.build(la.ConfigurationRecipeApi)
    quotes_api = api_factory.build(la.QuotesApi)
    property_definition_api = api_factory.build(la.PropertyDefinitionsApi)
    transaction_portfolios_api = api_factory.build(la.TransactionPortfoliosApi)
    portfolios_api = api_factory.build(la.PortfoliosApi)
    transaction_config_api = api_factory.build(la.TransactionConfigurationApi)
    print("All APIs built correctly")
except ApiException as e:
    print(e)

All APIs built correctly

## Create a scope and code for entities in the Notebook

Keep data segregated from other data in LUSID.

In [3]:
# Create a scope and code to segregate data in this Notebook from others
module_scope = "FBNTutorials"
module_code = "FlexRepo"
print(f"'{module_scope}\\{module_code}' scope and code created.")

'FBNTutorials\FlexRepo' scope and code created.

## Create property types

Create a SHK to split out underlying bond coupon cash in holding reports from other cash balances.

In [4]:
def create_property_type(property_domain, property_scope, property_code, data_type):
    property_type_request = lm.CreatePropertyDefinitionRequest(
        domain = property_domain,
        scope = property_scope,
        code = property_code,
        display_name = property_code,
        data_type_id = lm.ResourceId(scope = "system", code = data_type)
    )

    try:
        property_type_response = property_definition_api.create_property_definition(
            create_property_definition_request = property_type_request
        )
        print(f"Property type created with the following key: {property_type_response.key}")
        return property_type_response.key
    except ApiException as e:
        if json.loads(e.body)["name"] == "PropertyAlreadyExists":
            logging.info(
                f"Property type with the following key already exists: {property_type_request.domain}/{property_type_request.scope}/{property_type_request.code}"
            )  
        return f"{property_type_request.domain}/{property_type_request.scope}/{property_type_request.code}"

In [5]:
bond_coupon_shk = create_property_type("Transaction", "SHKs", "BondCollateralCoupons", "string")

INFO:root:Property type with the following key already exists: Transaction/SHKs/BondCollateralCoupons

## Create transaction types and sides

Required for both explicit purchase transactions and for transactions automatically generated by instrument events.

All created in a custom transaction type scope, which must be registered with the portfolios in which transactions are loaded.

In [6]:
def check_TT(tt, scope):
    try:
        tt_response = transaction_config_api.get_transaction_type(source = f"default", type = tt, scope=scope)
        print(f"\n{tt} transaction type:")
        display(lusid_response_to_data_frame(tt_response.aliases))
        display(lusid_response_to_data_frame(tt_response.movements))
        display(lusid_response_to_data_frame(tt_response.calculations))
    except ApiException as e:
        print(e)
        
def check_side(side, scope):
    try:
        side_response = transaction_config_api.get_side_definition(scope = scope, side = side)
        print(f"\n{side} side:")
        side_response_df = lusid_response_to_data_frame(side_response).transpose()
        side_response_df.drop(side_response_df.filter(regex='links').columns, axis=1, inplace=True)
        display(side_response_df)  
    except ApiException as e:
        print(e)

### Create sides

Must be created before transaction types. Includes recreating the built-in `Side1` and `Side2` in the custom transaction type scope.

In [7]:
# Recreate Side1 in custom scope
side_definition = lm.SideDefinitionRequest(
    security = "Txn:LusidInstrumentId",
    currency = "Txn:TradeCurrency",
    rate = "Txn:TradeToPortfolioRate",
    units = "Txn:Units",
    amount = "Txn:TradeAmount"
)

try:
    response = transaction_config_api.set_side_definition(
        side = "Side1",
        scope= f"{module_scope}{module_code}",
        side_definition_request = side_definition
    )
    print("Success")
except ApiException as e:
    print(e)

Success

In [8]:
# Recreate Side2 in custom scope
side_definition = lm.SideDefinitionRequest(
    security = "Txn:SettleCcy",
    currency = "Txn:SettlementCurrency",
    rate = "SettledToPortfolioRate",
    units = "Txn:TotalConsideration",
    amount = "Txn:TotalConsideration"
)

try:
    response = transaction_config_api.set_side_definition(
        side = "Side2",
        scope= f"{module_scope}{module_code}",
        side_definition_request = side_definition
    )
    print("Success")
except ApiException as e:
    print(e)

Success

In [9]:
# Define custom 'Side1EnterRepo' to handle units for purchase transaction type
side_definition = lm.SideDefinitionRequest(
    security = "Txn:LusidInstrumentId",
    currency = "Txn:TradeCurrency",
    rate = "Txn:TradeToPortfolioRate",
    units = "Txn:Units",
    amount = "0", 
)

try:
    response = transaction_config_api.set_side_definition(
        side = "Side1EnterRepo",
        scope= f"{module_scope}{module_code}",
        side_definition_request = side_definition
    )
    print("Success")
except ApiException as e:
    print(e)

Success

In [10]:
# Define custom 'Side1EnterRepoCost' to handle cost for purchase transaction type
side_definition = lm.SideDefinitionRequest(
    security = "Txn:LusidInstrumentId",
    currency = "Txn:TradeCurrency",
    rate = "Txn:TradeToPortfolioRate",
    units = "0",
    amount = "Txn:TotalConsideration", 
)

try:
    response = transaction_config_api.set_side_definition(
        side = "Side1EnterRepoCost",
        scope= f"{module_scope}{module_code}",
        side_definition_request = side_definition
    )
    print("Success")
except ApiException as e:
    print(e)

Success

In [11]:
# Define custom 'Side1RepoCashTransfer' side to handle repurchase price for FlexibleRepoCashFlowEvent
side_definition = lm.SideDefinitionRequest(
    security = "Txn:LusidInstrumentId",
    currency = "Txn:TradeCurrency",
    rate = "Txn:TradeToPortfolioRate",
    units = "0",
    amount = "Txn:TotalConsideration", 
)

try:
    response = transaction_config_api.set_side_definition(
        side = "Side1RepoCashTransfer",
        scope= f"{module_scope}{module_code}",
        side_definition_request = side_definition
    )
    print("Success")
except ApiException as e:
    print(e)

Success

In [12]:
# Define custom 'Side1RepoInterestPayment' side to report interest for FlexibleRepoInterestPaymentEvent
side_definition = lm.SideDefinitionRequest(
    security = "Txn:LusidInstrumentId",
    currency = "Txn:TradeCurrency",
    rate = "Txn:TradeToPortfolioRate",
    units = "Txn:Units",
    amount = "Txn:TotalConsideration", 
)

try:
    response = transaction_config_api.set_side_definition(
        side = "Side1RepoInterestPayment",
        scope= f"{module_scope}{module_code}",
        side_definition_request = side_definition
    )
    print("Success")
except ApiException as e:
    print(e)

Success

### Create transaction types

Note transaction type calculations are deliberately *not* used for `FlexibleRepo`.

#### Create `EnterRepo` transaction type (to establish positions)

Three movements, two of which use custom sides.

In [13]:
transaction_type_definition = lm.TransactionTypeRequest(
    aliases = [
        lm.TransactionTypeAlias(
            type = "EnterRepo",
            description = "Open the contract",
            transaction_class = "Basic",
            transaction_roles = "AllRoles",
            is_default = False
        )
    ],
    movements = [
        lm.TransactionTypeMovement(
            movement_types = "StockMovement",
            side = "Side1EnterRepo",
            direction = 1
        ),
        lm.TransactionTypeMovement(
            movement_types = "CashReceivable",
            side = "Side2",
            direction = 1
        ),
        lm.TransactionTypeMovement(
            movement_types = "StockMovement",
            side = "Side1EnterRepoCost",
            direction = -1
        )
    ],
)

try:
    response = transaction_config_api.set_transaction_type(
        source = "default",
        scope = f"{module_scope}{module_code}",
        # Specify the primary alias name
        type = "EnterRepo",
        transaction_type_request = transaction_type_definition
    )
    print("Success")
except ApiException as e:
    print(e)

Success

### Create `FlexibleRepoCashTransfer` transaction type (to handle `FlexibleRepoCashFlowEvent`)

The `StockMovement` uses a custom side.

In [14]:
transaction_type_definition = lm.TransactionTypeRequest(
    aliases = [
        lm.TransactionTypeAlias(
            type = "FlexibleRepoCashTransfer",
            description = "Transaction type for transactions automatically generated by FlexibleRepoCashFlowEvent",
            transaction_class = "Basic",
            transaction_roles = "AllRoles",
            is_default = False
        )
    ],
    movements = [
        lm.TransactionTypeMovement(
            name = "Transfer cash",
            movement_types = "CashReceivable",
            side = "Side2",
            direction = 1
        ),
        lm.TransactionTypeMovement(
            name = "Impact cost of stock",
            movement_types = "StockMovement",
            side = "Side1RepoCashTransfer",
            direction = -1
        )
    ]
)
# Replace transaction type in LUSID    
try:
    response = transaction_config_api.set_transaction_type(
        # The source must be 'default' to use the built-in instrument event transaction template
        source = "default",
        scope = f"{module_scope}{module_code}",
        # Specify the primary alias name
        type = "FlexibleRepoCashTransfer",
        transaction_type_request = transaction_type_definition
    )
    print("Success")
except lu.ApiException as e:
    print(e)

Success

### Create `FlexibleRepoCollateralTransfer` transaction type (to handle `FlexibleRepoCollateralEvent`)

In [15]:
transaction_type_definition = lm.TransactionTypeRequest(
    aliases = [
        lm.TransactionTypeAlias(
            type = "FlexibleRepoCollateralTransfer",
            description = "Transaction type for transactions automatically generated by FlexibleRepoCollateralEvent",
            transaction_class = "Basic",
            transaction_roles = "AllRoles",
            is_default = False
        )
    ],
    movements = [
        lm.TransactionTypeMovement(
            name = "Transfer collateral",
            movement_types = "StockMovement",
            side = "Side1",
            direction = 1
        )
    ]
)

try:
    response = transaction_config_api.set_transaction_type(
        # The source must be 'default' to use the built-in instrument event transaction template        
        source = "default",
        scope = f"{module_scope}{module_code}",
        # Specify the primary alias name
        type = "FlexibleRepoCollateralTransfer",
        transaction_type_request = transaction_type_definition
    )
    print("Success")
except lu.ApiException as e:
    print(e)

Success

### Create `FlexibleRepoInterestPayment` transaction type (to handle `FlexibleRepoInterestPaymentEvent`)

The `Carry` movement has a custom side.

In [16]:
transaction_type_definition = lm.TransactionTypeRequest(
    aliases = [
        lm.TransactionTypeAlias(
            type = "FlexibleRepoInterestPayment",
            description = "Transaction type for transactions automatically generated by FlexibleRepoInterestPaymentEvent",
            transaction_class = "Basic",
            transaction_roles = "AllRoles",
            is_default = False
        )
    ],
    movements = [
        lm.TransactionTypeMovement(
            name = "Add repo interest",
            movement_types = "CashAccrual",
            side = "Side2",
            direction = 1
        ),
        lm.TransactionTypeMovement(
            name = "Report repo interest",
            movement_types = "Carry",
            side = "Side1RepoInterestPayment",
            direction = 1
        )
    ]
)
    
try:
    response = transaction_config_api.set_transaction_type(
        # The source must be 'default' to use the built-in instrument event transaction template
        source = "default",
        scope = f"{module_scope}{module_code}",
        # Specify the primary alias name
        type = "FlexibleRepoInterestPayment",
        transaction_type_request = transaction_type_definition
    )
    print("Success")
except lu.ApiException as e:
    print(e)

Success

### Create `Maturity` transaction type (to handle `MaturityEvent`)

In [17]:
transaction_type_definition = lm.TransactionTypeRequest(
    aliases = [
        lm.TransactionTypeAlias(
            type = "Maturity",
            description = "Type for maturity event for various instruments",
            transaction_class = "Basic",
            transaction_roles = "AllRoles",
            is_default = False
        )
    ],
    movements = [
        lm.TransactionTypeMovement(
            name = "Set holding to zero",
            movement_types = "StockMovement",
            direction = -1,
            side = "Side1",
        ),
    ]
)

try:
    response = transaction_config_api.set_transaction_type(
        # The source must be 'default' to use the built-in instrument event transaction template
        source = "default",
        scope = f"{module_scope}{module_code}",
        # Specify the primary alias name
        type = "Maturity",
        transaction_type_request = transaction_type_definition
    )
    print("Success")
except lu.ApiException as e:
    print(e)

Success

### Create `BondCoupon` transaction type (for mandatory `BondCouponEvent`)

This is for the underlying `Bond` collateral instrument while it's part of the `FlexibleRepo`. See https://support.lusid.com/docs/handling-bond-coupon-principal-and-maturity-instrument-lifecycle-events.

In [18]:
transaction_type_definition = lm.TransactionTypeRequest(
    aliases = [
        lm.TransactionTypeAlias(
            type = "BondCoupon",
            description = "Type for bond coupon event",
            transaction_class = "Basic",
            transaction_roles = "AllRoles",
            is_default = False
        )
    ],
    movements = [
        # Create a positive movement that increases a separate cash balance (under SHK) by the gross coupon payment
        lm.TransactionTypeMovement(
            name = "Add coupon to separate cash balance",
            movement_types = "CashAccrual",
            direction = 1,
            side = "Side2",
            mappings = [
                lm.TransactionTypePropertyMapping (
                    property_key = f"{bond_coupon_shk}",
                    set_to = "BondCollateralCoupons",
                )
            ],
        ),
        lm.TransactionTypeMovement(
            name = "Report the coupon as a flow out of the investment",
            movement_types = "Carry",
            direction = 1,
            side = "Side1",
        )
    ]
)

try:
    response = transaction_config_api.set_transaction_type(
        # The source must be 'default' to use the built-in instrument event transaction template
        source = "default",
        scope = f"{module_scope}{module_code}",
        # Specify the primary alias name
        type = "BondCoupon",
        transaction_type_request = transaction_type_definition
    )
    print("Success")
except lu.ApiException as e:
    print(e)

Success

### Create `StockIn` transaction type in custom scope

This is to simply establish a position in the underlying `Bond` instrument in portfolios so collateral units can be transferred.

Note transaction type calculations are enabled to calculate accrual correctly; see https://support.lusid.com/docs/what-is-a-transaction-type-calculation#txnbondinterest-calculation.

In [19]:
transaction_type_definition = lm.TransactionTypeRequest(
    aliases = [
        lm.TransactionTypeAlias(
            type = "StockIn",
            description = "Transfer in",
            transaction_class = "StockTransfers",
            transaction_roles = "Longer",
            is_default = False
        )
    ],
    movements = [
        lm.TransactionTypeMovement(
            movement_types = "StockMovement",
            direction = 1,
            side = "Side1",
        )
    ],
    calculations = [
        lm.TransactionTypeCalculation(
            type = "Txn:BondInterest"
        ),
        lm.TransactionTypeCalculation(
            type = "Txn:GrossConsideration"
        ),
        lm.TransactionTypeCalculation(
            type = "DeriveTotalConsideration",
            formula = "Txn:GrossConsideration"
        )
    ]
)

try:
    response = transaction_config_api.set_transaction_type(
        source = "default",
        scope = f"{module_scope}{module_code}",
        # Specify the primary alias name
        type = "StockIn",
        transaction_type_request = transaction_type_definition
    )
    print("Success")
except lu.ApiException as e:
    print(e)

Success

In [20]:
check_side("Side1", f"{module_scope}{module_code}")
check_side("Side2", f"{module_scope}{module_code}")

check_TT("EnterRepo", f"{module_scope}{module_code}")
check_side("Side1EnterRepo", f"{module_scope}{module_code}")
check_side("Side1EnterRepoCost", f"{module_scope}{module_code}")

check_TT("FlexibleRepoCashTransfer", f"{module_scope}{module_code}")
check_side("Side1RepoCashTransfer", f"{module_scope}{module_code}")

check_TT("FlexibleRepoCollateralTransfer", f"{module_scope}{module_code}")

check_TT("FlexibleRepoInterestPayment", f"{module_scope}{module_code}")
check_side("Side1RepoInterestPayment", f"{module_scope}{module_code}")

check_TT("Maturity", f"{module_scope}{module_code}")

# For underlying bond collateral
check_TT("BondCoupon", f"{module_scope}{module_code}")
check_TT("StockIn", f"{module_scope}{module_code}")

Side1 side:

,side,security,currency,rate,units,amount,notional_amount,current_face
response_values,Side1,Txn:LusidInstrumentId,Txn:TradeCurrency,Txn:TradeToPortfolioRate,Txn:Units,Txn:TradeAmount,0,None

Side2 side:

,side,security,currency,rate,units,amount,notional_amount,current_face
response_values,Side2,Txn:SettleCcy,Txn:SettlementCurrency,SettledToPortfolioRate,Txn:TotalConsideration,Txn:TotalConsideration,0,None

EnterRepo transaction type:

,type,description,transaction_class,transaction_roles,is_default
0,EnterRepo,Open the contract,Basic,AllRoles,False

,movement_types,side,direction,properties,mappings,movement_options,condition,settlement_mode
0,StockMovement,Side1EnterRepo,1,{},[],[],,Internal
1,CashReceivable,Side2,1,{},[],[],,Internal
2,StockMovement,Side1EnterRepoCost,-1,{},[],[],,Internal

Empty DataFrame
Columns: []
Index: []

Side1EnterRepo side:

,side,security,currency,rate,units,amount,notional_amount,current_face
response_values,Side1EnterRepo,Txn:LusidInstrumentId,Txn:TradeCurrency,Txn:TradeToPortfolioRate,Txn:Units,0,0,None

Side1EnterRepoCost side:

,side,security,currency,rate,units,amount,notional_amount,current_face
response_values,Side1EnterRepoCost,Txn:LusidInstrumentId,Txn:TradeCurrency,Txn:TradeToPortfolioRate,0,Txn:TotalConsideration,0,None

FlexibleRepoCashTransfer transaction type:

,type,description,transaction_class,transaction_roles,is_default
0,FlexibleRepoCashTransfer,Transaction type for transactions automaticall...,Basic,AllRoles,False

,movement_types,side,direction,properties,mappings,name,movement_options,condition,settlement_mode
0,CashReceivable,Side2,1,{},[],Transfer cash,[],,Internal
1,StockMovement,Side1RepoCashTransfer,-1,{},[],Impact cost of stock,[],,Internal

Empty DataFrame
Columns: []
Index: []

Side1RepoCashTransfer side:

,side,security,currency,rate,units,amount,notional_amount,current_face
response_values,Side1RepoCashTransfer,Txn:LusidInstrumentId,Txn:TradeCurrency,Txn:TradeToPortfolioRate,0,Txn:TotalConsideration,0,None

FlexibleRepoCollateralTransfer transaction type:

,type,description,transaction_class,transaction_roles,is_default
0,FlexibleRepoCollateralTransfer,Transaction type for transactions automaticall...,Basic,AllRoles,False

,movement_types,side,direction,properties,mappings,name,movement_options,condition,settlement_mode
0,StockMovement,Side1,1,{},[],Transfer collateral,[],,Internal

Empty DataFrame
Columns: []
Index: []

FlexibleRepoInterestPayment transaction type:

,type,description,transaction_class,transaction_roles,is_default
0,FlexibleRepoInterestPayment,Transaction type for transactions automaticall...,Basic,AllRoles,False

,movement_types,side,direction,properties,mappings,name,movement_options,condition,settlement_mode
0,CashAccrual,Side2,1,{},[],Add repo interest,[],,Internal
1,Carry,Side1RepoInterestPayment,1,{},[],Report repo interest,[],,Internal

Empty DataFrame
Columns: []
Index: []

Side1RepoInterestPayment side:

,side,security,currency,rate,units,amount,notional_amount,current_face
response_values,Side1RepoInterestPayment,Txn:LusidInstrumentId,Txn:TradeCurrency,Txn:TradeToPortfolioRate,Txn:Units,Txn:TotalConsideration,0,None

Maturity transaction type:

,type,description,transaction_class,transaction_roles,is_default
0,Maturity,Type for maturity event for various instruments,Basic,AllRoles,False

,movement_types,side,direction,properties,mappings,name,movement_options,condition,settlement_mode
0,StockMovement,Side1,-1,{},[],Set holding to zero,[],,Internal

Empty DataFrame
Columns: []
Index: []

BondCoupon transaction type:

,type,description,transaction_class,transaction_roles,is_default
0,BondCoupon,Type for bond coupon event,Basic,AllRoles,False

,movement_types,side,direction,properties,mappings.0.property_key,mappings.0.set_to,name,movement_options,condition,settlement_mode,mappings
0,CashAccrual,Side2,1,{},Transaction/SHKs/BondCollateralCoupons,BondCollateralCoupons,Add coupon to separate cash balance,[],,Internal,NaN
1,Carry,Side1,1,{},NaN,NaN,Report the coupon as a flow out of the investment,[],,Internal,[]

Empty DataFrame
Columns: []
Index: []

StockIn transaction type:

      type  description transaction_class transaction_roles  is_default
0  StockIn  Transfer in    StockTransfers            Longer       False

,movement_types,side,direction,properties,mappings,movement_options,condition,settlement_mode
0,StockMovement,Side1,1,{},[],[],,Internal

                       type                 formula
0          Txn:BondInterest                    None
1    Txn:GrossConsideration                    None
2  DeriveTotalConsideration  Txn:GrossConsideration

## Master instruments

For more information, see https://support.lusid.com/docs/modelling-repurchase-agreements-in-lusid#mastering-an-instrument.

### Set up global numeric variables for `FlexibleRepo`

**`purchasePrice`**:  If `collateralValue` is known, then either specify `haircut` or `margin` and LUSID calculates the purchase price for you. But you can specify an explicit `purchasePrice` if you want.

**`repurchasePrice`**:  If `repoRate` is known, specify it in the `FixedSchedule` or `FloatSchedule` for a `FlexibleRepo` and LUSID calculates the repurchase price for you. But you can specify an explicit `repurchasePrice` if you want.

In [21]:
myCollateralValue = 1100000

myHaircut = 0.09090909090909090909
myMargin = None
myPurchasePrice = None

myRepoRate = 0.05
myRepurchasePrice = None

In [22]:
def master_instrument(assetClass, id, currency, accrualBasis, start, end, repoActor, repoClosure, transferUnits):
    
    if repoClosure == "TermRepo":
        tenor = "1T"
    else:
        tenor = "1W"

    if assetClass == "bond":
        instrument_request = {
            id: lm.InstrumentDefinition(
                name = id,
                identifiers = {"ClientInternal": lm.InstrumentIdValue(value = id)},
                definition = lm.Bond(
                    instrument_type = "Bond", 
                    dom_ccy = currency,
                    start_date = to_date(start),
                    maturityDate=to_date(end),
                    flow_conventions = lm.FlowConventions(
                        currency = currency,
                        payment_frequency = '1M',
                        day_count_convention = accrualBasis,
                        roll_convention = '28',
                        payment_calendars = [],
                        reset_calendars = [],
                    ),
                    principal = 1000,
                    coupon_rate = 0.25,
                )
            )
        }
    if assetClass == "flexrepo":
        instrument_request = {
            id: lm.InstrumentDefinition(
                name = id,
                identifiers = {"ClientInternal": lm.InstrumentIdValue(value = id)},
                definition = lm.FlexibleRepo(
                    instrument_type = "FlexibleRepo", 
                    start_date = to_date(start),
                    maturity_date = to_date(end),   # Required for TermRepo. For OpenRepo, specify an open-ended date
                    buyerOrSeller = repoActor,
                    repoCcy=currency,
                    repoType=repoClosure,
                    collateral = lm.Collateral(
                        buyerReceivesCashflows=False,
                        buyerReceivesCorporateActionPayments=False,
                        collateralInstruments = [
                            lm.CollateralInstrument(
                                units = 1, 
                                instrument = lm.MasteredInstrument(
                                    identifiers={"Instrument/default/ClientInternal": "BondCollateral"},
                                    instrument_type="MasteredInstrument"
                                )
                            )
                        ],
                        collateralValue=myCollateralValue,                
                    ),
                    isCollateralTransferActivated=transferUnits,                   
                    haircut = myHaircut,
                    margin=myMargin,
                    purchasePrice = myPurchasePrice,
                    # Can be single FixedSchedule or FloatSchedule
                    repo_rate_schedules=[lm.FixedSchedule(
                        schedule_type = 'FixedSchedule',
                        start_date = to_date(start),  # Same as flex repo itself
                        maturity_date = to_date(end),  # Same as flex repo itself
                        flow_conventions = lm.FlowConventions(
                            currency = currency,
                            payment_frequency = tenor,  # Must be 1T for TermRepo, same as openRepoRollingPeriod for OpenRepo
                            day_count_convention = accrualBasis,
                            roll_convention = 'None',
                            payment_calendars = [],
                            reset_calendars = [],
                        ),
                        coupon_rate = myRepoRate,
                        notional = 1,
                        payment_currency = currency,
                    )],
                    repurchasePrice = myRepurchasePrice,
                    openRepoRollingPeriod = tenor, # Required for OpenRepo; has no effect on TermRepo
                )
            )
        }
    
    try:
        instrument_response = instruments_api.upsert_instruments(
            request_body = instrument_request,
            scope = f"{module_scope}{module_code}"
        )
        # Return LUID from (only) Instrument object
        return list(instrument_response.values.values())[0].lusid_instrument_id
    except ApiException as e:
        print(e)

In [23]:
luid_dict = {}
luid_dict["BondCollateral"] = master_instrument("bond", "BondCollateral", "GBP", "Act365", "2015-03-28", "2030-03-28", "", "", "")

In [24]:
# Term Repo
luid_dict["Buyer-TermFlexRepo"] = master_instrument("flexrepo", "Buyer-TermFlexRepo", "GBP", "Act365", "2025-01-02", "2025-03-31", "Buyer", "TermRepo", True)
luid_dict["Seller-TermFlexRepo"] = master_instrument("flexrepo", "Seller-TermFlexRepo", "GBP", "Act365", "2025-01-02", "2025-03-31", "Seller", "TermRepo", True)

# Open Repo - note long-dated maturity date
# luid_dict["Buyer-OpenFlexRepo"] = master_instrument("flexrepo", "Buyer-OpenFlexRepo", "GBP", "Act365", "2025-01-02", "2199-12-31", "Buyer", "OpenRepo", True)
# luid_dict["Seller-OpenFlexRepo"] = master_instrument("flexrepo", "Seller-OpenFlexRepo", "GBP", "Act365", "2025-01-02", "2199-12-31", "Seller", "OpenRepo", True)

for k, v in luid_dict.items():
    print(f"{k}: {v}")

BondCollateral: LUID_00003H1O
Buyer-TermFlexRepo: LUID_00003H1P
Seller-TermFlexRepo: LUID_00003H1Q

In [25]:
def list_instrs():
    instr_response = instruments_api.list_instruments(scope=f"{module_scope}{module_code}")
    instr_response_df = lusid_response_to_data_frame(instr_response)
    instr_response_df.drop(instr_response_df.filter(regex='version|href|staged').columns, axis=1, inplace=True)
    display(instr_response_df.transpose())

list_instrs()

,0,1,2
scope,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo
lusid_instrument_id,LUID_00003H1O,LUID_00003H1P,LUID_00003H1Q
name,BondCollateral,Buyer-TermFlexRepo,Seller-TermFlexRepo
identifiers.ClientInternal,BondCollateral,Buyer-TermFlexRepo,Seller-TermFlexRepo
identifiers.LusidInstrumentId,LUID_00003H1O,LUID_00003H1P,LUID_00003H1Q
properties,[],[],[]
instrument_definition.instrument_type,Bond,FlexibleRepo,FlexibleRepo
state,Active,Active,Active
asset_class,Credit,InterestRates,InterestRates
dom_ccy,GBP,GBP,GBP
relationships,[],[],[]
data_model_membership.membership,[],[],[]

## Create a recipe

Must be specified as a portfolio recipe to enable instrument events. Can also be used as a valuation recipe.

Note the pricing models have been changed from the defaults for both the `Bond` collateral (to `BondLookupPricer`) and all `FlexibleRepo` instruments (to `FlexibleRepoSimplePricer`).

In [26]:
recipe = lm.ConfigurationRecipe(
    # Put the recipe in the same scope as portfolios
    scope = module_scope,
    # Give the recipe a unique code in the scope
    code = f"{module_code}-FlexibleRepoSimplePricer",
    description = "A recipe to value a repurchase agreement and the underlying collateral",
    market = lm.MarketContext(
        market_rules = [
            # Look up FX spot rates in the LUSID quote store, if needed
            lm.MarketDataKeyRule(
                key = "Fx.CurrencyPair.*",
                supplier = "Lusid",
                data_scope = f"{module_scope}{module_code}",
                quote_type = "Rate",
                field = "mid",
                quote_interval = "1D.0D",
            ),
            lm.MarketDataKeyRule(
                key = "Quote.*.*",
                supplier = "Lusid",
                data_scope = f"{module_scope}{module_code}",
                quote_type = "Price",
                field = "mid",
                quote_interval = "1D.0D",
            )
        ]
    ),
    # Change pricing models
    pricing=lm.PricingContext(
        model_rules=[
            lm.VendorModelRule(
                supplier="Lusid",
                model_name="FlexibleRepoSimplePricer",
                instrument_type="FlexibleRepo"
            ),
            lm.VendorModelRule(
                supplier="Lusid",
                model_name="BondLookupPricer",
                instrument_type="Bond"
            )
        ],
        accrualDefinition="EOD"
    )
)

try:
    recipe_api.upsert_configuration_recipe(
        upsert_recipe_request = lm.UpsertRecipeRequest(
            configuration_recipe = recipe
        )
    )
    print("Success")
except ApiException as e:
    print(e)

Success

In [27]:
# Confirm upsert and show the many options that are automatically set to default values by LUSID.
config_recipe = recipe_api.list_configuration_recipes(filter=f"value.scope eq '{module_scope}' and value.code startswith '{module_code}'")
config_recipe_df = lusid_response_to_data_frame(config_recipe)
display(config_recipe_df.transpose())

,0,1,2,3
value.scope,FBNTutorials,FBNTutorials,FBNTutorials,FBNTutorials
value.code,FlexRepoOpen-FlexibleRepoSimplePricer,FlexRepo-FlexibleRepoSimplePricer,FlexRepoTest2-FlexibleRepoSimplePricer,FlexRepoTermTest1-FlexibleRepoSimplePricer
value.market.market_rules.0.key,Fx.CurrencyPair.*,Fx.CurrencyPair.*,Fx.CurrencyPair.*,Fx.CurrencyPair.*
value.market.market_rules.0.supplier,Lusid,Lusid,Lusid,Lusid
value.market.market_rules.0.data_scope,FBNTutorialsFlexRepoOpen,FBNTutorialsFlexRepo,FBNTutorialsFlexRepoTest2,FBNTutorialsFlexRepoTermTest1
value.market.market_rules.0.quote_type,Rate,Rate,Rate,Rate
value.market.market_rules.0.var_field,mid,mid,mid,mid
value.market.market_rules.0.quote_interval,1D.0D,1D.0D,1D.0D,1D.0D
value.market.market_rules.0.price_source,,,,
value.market.market_rules.0.source_system,Lusid,Lusid,Lusid,Lusid
value.market.market_rules.0.fall_through_on_access_denied,False,False,False,False
value.market.market_rules.1.key,Quote.*.*,Quote.*.*,Quote.*.*,Quote.*.*
value.market.market_rules.1.supplier,Lusid,Lusid,Lusid,Lusid
value.market.market_rules.1.data_scope,FBNTutorialsFlexRepoOpen,FBNTutorialsFlexRepo,FBNTutorialsFlexRepoTest2,FBNTutorialsFlexRepoTermTest1
value.market.market_rules.1.quote_type,Price,Price,Price,Price
value.market.market_rules.1.var_field,mid,mid,mid,mid
value.market.market_rules.1.quote_interval,1D.0D,1D.0D,1D.0D,1D.0D
value.market.market_rules.1.price_source,,,,
value.market.market_rules.1.source_system,Lusid,Lusid,Lusid,Lusid
value.market.market_rules.1.fall_through_on_access_denied,False,False,False,False
value.market.options.default_supplier,Lusid,Lusid,Lusid,Lusid
value.market.options.default_instrument_code_type,LusidInstrumentId,LusidInstrumentId,LusidInstrumentId,LusidInstrumentId
value.market.options.default_scope,default,default,default,default
value.market.options.attempt_to_infer_missing_fx,False,False,False,False
value.market.options.calendar_scope,CoppClarkHolidayCalendars,CoppClarkHolidayCalendars,CoppClarkHolidayCalendars,CoppClarkHolidayCalendars
value.market.options.convention_scope,Conventions,Conventions,Conventions,Conventions
value.market.specific_rules,[],[],[],[]
value.market.grouped_market_rules,[],[],[],[]
value.pricing.model_rules.0.supplier,Lusid,Lusid,Lusid,Lusid
value.pricing.model_rules.0.model_name,FlexibleRepoSimplePricer,FlexibleRepoSimplePricer,FlexibleRepoSimplePricer,FlexibleRepoSimplePricer
value.pricing.model_rules.0.instrument_type,FlexibleRepo,FlexibleRepo,FlexibleRepo,FlexibleRepo
value.pricing.model_rules.0.parameters,,,,
value.pricing.model_rules.0.model_options.model_options_type,EmptyModelOptions,EmptyModelOptions,EmptyModelOptions,EmptyModelOptions
value.pricing.model_rules.0.instrument_id,,,,
value.pricing.model_rules.0.address_key_filters,[],[],[],[]
value.pricing.model_rules.1.supplier,Lusid,Lusid,Lusid,Lusid
value.pricing.model_rules.1.model_name,BondLookupPricer,BondLookupPricer,BondLookupPricer,BondLookupPricer
value.pricing.model_rules.1.instrument_type,Bond,Bond,Bond,Bond
value.pricing.model_rules.1.parameters,,,,
value.pricing.model_rules.1.model_options.model_options_type,EmptyModelOptions,EmptyModelOptions,EmptyModelOptions,EmptyModelOptions
value.pricing.model_rules.1.instrument_id,,,,
value.pricing.model_rules.1.address_key_filters,[],[],[],[]
value.pricing.model_choice,{},{},{},{}
value.pricing.options.model_selection.library,Lusid,Lusid,Lusid,Lusid
value.pricing.options.model_selection.model,SimpleStatic,SimpleStatic,SimpleStatic,SimpleStatic
value.pricing.options.use_instrument_type_to_determine_pricer,False,False,False,False
value.pricing.options.allow_any_instruments_with_sec_uid_to_price_off_lookup,False,False,False,False
value.pricing.options.allow_partially_successful_evaluation,False,False,False,False
value.pricing.options.produce_separate_result_for_linear_otc_legs,False,False,False,False
value.pricing.options.fx_forward_contracts_as_units_in_both_legs,False,False,False,False
value.pricing.options.enable_use_of_cached_unit_results,False,False,False,False
value.pricing.options.window_valuation_on_instrument_start_end,False,False,False,False
value.pricing.options.remove_contingent_cashflows_in_payment_diary,False,False,False,False
value.pricing.options.use_child_sub_holding_keys_for_portfolio_expansion,False,False,False,False
value.pricing.options.validate_domestic_and_quote_currencies_are_consistent,False,False,False,False
value.pricing.options.mbs_valuation_using_holding_current_face,False,False,False,False
value.pricing.options.convert_srs_cash_flows_to_portfolio_currency,False,False,False,False
value.pricing.options.conserved_quantity_for_lookthrough_expansion,PV,PV,PV,PV
value.pricing.options.return_zero_pv.instrument_matured,False,False,False,False
value.pricing.options.enable_leg_level_inference_for_custom_srs_columns,False,False,False,False
value.pricing.options.use_instrument_scale_factor_as_default,False,False,False,False
value.pricing.result_data_rules,[],[],[],[]
value.pricing.holding_pricing_info.fallback_field,None,None,None,None
value.pricing.holding_pricing_info.override_field,None,None,None,None
value.pricing.holding_pricing_info.specific_fallbacks,[],[],[],[]
value.pricing.holding_pricing_info.specific_overrides,[],[],[],[]
value.pricing.accrual_definition,EOD,EOD,EOD,EOD
value.aggregation.options.use_ansi_like_syntax,False,False,False,False
value.aggregation.options.allow_partial_entitlement_success,False,False,False,False
value.aggregation.options.apply_iso4217_rounding,False,False,False,False
value.description,A recipe to value a repurchase agreement and t...,A recipe to value a repurchase agreement and t...,A recipe to value a repurchase agreement and t...,A recipe to value a repurchase agreement and t...
value.holding.tax_lot_level_holdings,True,True,True,True

## Create a corporate action source

Required if `FlexibleRepoPartialClosureEvent` and/or `FlexibleRepoFullClosureEvent` are to be loaded as manual events. Must be created before portfolios.

In [28]:
corporate_action_sources_api = api_factory.build(la.CorporateActionSourcesApi)

ca_source_definition = lm.CreateCorporateActionSourceRequest(
    scope=module_scope,
    code=module_code,
    display_name=f"{module_scope}/{module_code} CAS",
    instrument_scopes = [f"{module_scope}{module_code}"]
)

try:
    corporate_action_sources_api.create_corporate_action_source(
        create_corporate_action_source_request = ca_source_definition
    )
    print(f"{module_scope}/{module_code} CAS created")
except ApiException as e:
    print(e)

FBNTutorials/FlexRepo CAS created

## Set up GBP transaction portfolios

One for the `Buyer` and one for the `Seller`.

With the portfolio recipe set to the recipe created above to enable instrument events, and the transaction type scope, corporate action source and sub-holding key registered.

In [29]:
ports = ["Buyer-Term", "Seller-Term"]
# ports = ["Buyer-Open", "Seller-Open"]
# ports = ["Buyer-Term", "Seller-Term", "Buyer-Open", "Seller-Open"]

In [30]:
def create_portfolio(name):
    portfolio_request=lm.CreateTransactionPortfolioRequest(
        display_name = f"{name}FlexRepo portfolio",
        code = f"{module_code}-{name}",
        # Set the portfolio currency
        base_currency = "GBP",
        # Must be before first transaction recorded
        created = datetime.strptime("2024-01-01", '%Y-%m-%d').replace(tzinfo=timezone.utc).isoformat(),
        # Attempt to resolve transactions to instruments in the custom scope before falling back to the default scope
        instrument_scopes = [f"{module_scope}{module_code}"],
        # Register SHKs
        sub_holding_keys = [bond_coupon_shk],
        # Register transaction type scope
        transactionTypeScope=f"{module_scope}{module_code}",
        # Register portfolio recipe
        instrumentEventConfiguration=lm.InstrumentEventConfiguration(
            recipeId=lm.ResourceId(
                scope=module_scope,
                code=f"{module_code}-FlexibleRepoSimplePricer"
            )
        ),
        # Register corporate action source
        corporate_action_source_id=lm.ResourceId(
            scope=module_scope,
            code=module_code
        )
    )

    try:
        portfolio_response=transaction_portfolios_api.create_portfolio(
            scope = module_scope,
            create_transaction_portfolio_request = portfolio_request
        )
        print(f"Portfolio with display name '{portfolio_response.display_name}' created effective {str(portfolio_response.created)}")
    except ApiException as e:
        print(e)

In [31]:
for port in ports:
    create_portfolio(port)

Portfolio with display name 'Buyer-TermFlexRepo portfolio' created effective 2024-01-01 00:00:00+00:00
Portfolio with display name 'Seller-TermFlexRepo portfolio' created effective 2024-01-01 00:00:00+00:00

### Confirm portfolio details

In [32]:
def get_port_details(port):
    portfolio_response = transaction_portfolios_api.get_details(scope = module_scope, code = f"{module_code}-{port}")
    portfolio_response_df = lusid_response_to_data_frame(portfolio_response).transpose()
    # Drop some noisy columns
    portfolio_response_df.drop(portfolio_response_df.filter(regex='version|href|staged|links|settlement').columns, axis=1, inplace=True)
    display(portfolio_response_df.transpose())
    
for port in ports:
    get_port_details(port)

                                                                           response_values
origin_portfolio_id.scope                                                     FBNTutorials
origin_portfolio_id.code                                               FlexRepo-Buyer-Term
base_currency                                                                          GBP
corporate_action_source_id.scope                                              FBNTutorials
corporate_action_source_id.code                                                   FlexRepo
sub_holding_keys.0                                  Transaction/SHKs/BondCollateralCoupons
instrument_scopes.0                                                   FBNTutorialsFlexRepo
accounting_method                                                                  Default
amortisation_method                                                         NoAmortisation
transaction_type_scope                                                FBNTutorialsFlexRepo
cash_gain_loss_calculation_date                                                    Default
instrument_event_configuration.transaction_temp...                                 default
instrument_event_configuration.recipe_id.scope                                FBNTutorials
instrument_event_configuration.recipe_id.code            FlexRepo-FlexibleRepoSimplePricer
amortisation_rule_set_id                                                              None
tax_rule_set_scope                                                                    None

                                                                           response_values
origin_portfolio_id.scope                                                     FBNTutorials
origin_portfolio_id.code                                              FlexRepo-Seller-Term
base_currency                                                                          GBP
corporate_action_source_id.scope                                              FBNTutorials
corporate_action_source_id.code                                                   FlexRepo
sub_holding_keys.0                                  Transaction/SHKs/BondCollateralCoupons
instrument_scopes.0                                                   FBNTutorialsFlexRepo
accounting_method                                                                  Default
amortisation_method                                                         NoAmortisation
transaction_type_scope                                                FBNTutorialsFlexRepo
cash_gain_loss_calculation_date                                                    Default
instrument_event_configuration.transaction_temp...                                 default
instrument_event_configuration.recipe_id.scope                                FBNTutorials
instrument_event_configuration.recipe_id.code            FlexRepo-FlexibleRepoSimplePricer
amortisation_rule_set_id                                                              None
tax_rule_set_scope                                                                    None

### Load transactions into portfolios

The `totalConsideration.amount` (ie. cost) needs to be `purchasePrice` to generate correct JE Lines. If this is not explicitly known then it can be calculated as `purchasePrice = collateralValue * (1 - haircut)`.

For a `Buyer` the total consideration must be signed negative, and for a `Seller` it must be signed positive. See https://support.lusid.com/docs/modelling-repurchase-agreements-in-lusid#booking-a-transaction-to-establish-a-position.

In [33]:
tc = myCollateralValue * (1 - myHaircut)
print(tc)

1000000.0

In [34]:
# Create convenience function
def create_transactions(port, txnid, tttype, luid, tradedate, price, quantity, tc, ccy):   
    create_txn_request = {
        "number_one": lm.TransactionRequest(
            transaction_id=txnid,
            type=tttype,
            instrument_identifiers = {"Instrument/default/LusidInstrumentId": luid},
            transaction_date=tradedate,
            settlement_date=tradedate,
            units=quantity,
            transaction_currency = ccy,
            transaction_price = lm.TransactionPrice(
                price = 0,
                type = "Price"
            ),
            total_consideration = lm.CurrencyAndAmount(
                amount = tc,
                currency = ccy,
            )
        )
    }
    
    try:
        create_txn_response = transaction_portfolios_api.batch_upsert_transactions(
            scope = f"{module_scope}",
            code = f"{module_code}-{port}",
            success_mode="Partial",
            request_body = create_txn_request
        )
        print(create_txn_response.failed) if create_txn_response.failed else print("Success")
    except ApiException as e:
        print(e)

In [35]:
# Buy `Bond` collateral in both portfolios before start date of `FlexibleRepo`, at zero cost
for port in ports:
    create_transactions(port, "Txn01", "StockIn", luid_dict["BondCollateral"], "2025-01-01", 100, 3, 0, "GBP")

# Buyer portfolio - total consideration must be negative
create_transactions(ports[0], "Txn02", "EnterRepo", luid_dict[f"{ports[0]}FlexRepo"], "2025-01-01", 0, 1, -tc, "GBP")

# Seller portfolio - total consideration must be positive
create_transactions(ports[1], "Txn02", "EnterRepo", luid_dict[f"{ports[1]}FlexRepo"], "2025-01-01", 0, 1, tc, "GBP")

Success
Success
Success
Success

### Confirm positions and audit output transactions

In [36]:
def get_portfolio_holdings(port, date):      
    if date == "today":
        date = str(datetime.datetime.now().replace(microsecond=0))
    
    try:
        get_holdings_response = transaction_portfolios_api.get_holdings(
            scope = module_scope, 
            code = f"{module_code}-{port}",
            effective_at = datetime.strptime(date, '%Y-%m-%d %H:%M:%S').replace(tzinfo=timezone.utc).isoformat(),
            property_keys=["Instrument/default/Name"]
        )
        get_holdings_response_df = lusid_response_to_data_frame(get_holdings_response)
        get_holdings_response_df.rename(columns = {
           "sub_holding_keys.Transaction/SHKs/BondCollateralCoupons.value.label_value": "SHK",
           "properties.Instrument/default/Name.value.label_value": "instrument"}, inplace = True)        
        # Drop some noisy columns
        get_holdings_response_df.drop(get_holdings_response_df.filter(regex='properties|sub_holding_keys').columns, axis=1, inplace=True)
        display(get_holdings_response_df)
    except ApiException as e:
        print(e)

In [37]:
def get_output_transactions(port, start, end):
    try:
        output_transactions_response = transaction_portfolios_api.build_transactions(
            scope = module_scope, 
            code = f"{module_code}-{port}",
            transaction_query_parameters = lm.TransactionQueryParameters(
                start_date = datetime.strptime(start, '%Y-%m-%d').replace(tzinfo=timezone.utc).isoformat(),
                end_date = datetime.strptime(end, '%Y-%m-%d').replace(tzinfo=timezone.utc).isoformat()
            )
        )
        output_transactions_response_df = lusid_response_to_data_frame(output_transactions_response)
        display(output_transactions_response_df.transpose())
    except ApiException as e:
        print(e)

In [38]:
for port in ports:
    print(f"\n{port}")
    get_portfolio_holdings(port, "2025-01-01 00:00:00")   # Transaction date
    get_portfolio_holdings(port, "2025-01-02 00:00:00")   # Instrument start date
    get_portfolio_holdings(port, "2025-03-31 00:00:00")   # Instrument maturity date

Buyer-Term

,instrument_scope,instrument_uid,SHK,instrument,holding_type,units,settled_units,cost.amount,cost.currency,cost_portfolio_ccy.amount,cost_portfolio_ccy.currency,currency,holding_type_name,holding_id,notional_cost.amount,notional_cost.currency,amortised_cost.amount,amortised_cost.currency,amortised_cost_portfolio_ccy.amount,amortised_cost_portfolio_ccy.currency,variation_margin.amount,variation_margin.currency,variation_margin_portfolio_ccy.amount,variation_margin_portfolio_ccy.currency,settlement_schedule,unsettled_units,overdue_units
0,FBNTutorialsFlexRepo,LUID_00003H1O,<Not Classified>,BondCollateral,P,3.00,3.00,0.00,GBP,0.00,GBP,GBP,Position,81088532,0.00,GBP,0.00,GBP,0.00,GBP,0.00,GBP,0.00,GBP,[],0.00,0.00
1,FBNTutorialsFlexRepo,LUID_00003H1P,<Not Classified>,Buyer-TermFlexRepo,P,1.00,1.00,"1,000,000.00",GBP,"1,000,000.00",GBP,GBP,Position,81088533,0.00,GBP,"1,000,000.00",GBP,"1,000,000.00",GBP,0.00,GBP,0.00,GBP,[],0.00,0.00
2,default,CCY_GBP,<Not Classified>,GBP,B,"-1,000,000.00","-1,000,000.00","-1,000,000.00",GBP,"-1,000,000.00",GBP,GBP,Balance,81088534,0.00,GBP,"-1,000,000.00",GBP,"-1,000,000.00",GBP,0.00,GBP,0.00,GBP,[],0.00,0.00

,instrument_scope,instrument_uid,SHK,instrument,holding_type,units,settled_units,cost.amount,cost.currency,cost_portfolio_ccy.amount,cost_portfolio_ccy.currency,currency,holding_type_name,holding_id,notional_cost.amount,notional_cost.currency,amortised_cost.amount,amortised_cost.currency,amortised_cost_portfolio_ccy.amount,amortised_cost_portfolio_ccy.currency,variation_margin.amount,variation_margin.currency,variation_margin_portfolio_ccy.amount,variation_margin_portfolio_ccy.currency,settlement_schedule,unsettled_units,overdue_units
0,FBNTutorialsFlexRepo,LUID_00003H1O,<Not Classified>,BondCollateral,P,4.00,4.00,0.00,GBP,0.00,GBP,GBP,Position,81088532,0.00,GBP,0.00,GBP,0.00,GBP,0.00,GBP,0.00,GBP,[],0.00,0.00
1,FBNTutorialsFlexRepo,LUID_00003H1P,<Not Classified>,Buyer-TermFlexRepo,P,1.00,1.00,"1,000,000.00",GBP,"1,000,000.00",GBP,GBP,Position,81088533,0.00,GBP,"1,000,000.00",GBP,"1,000,000.00",GBP,0.00,GBP,0.00,GBP,[],0.00,0.00
2,default,CCY_GBP,<Not Classified>,GBP,B,"-1,000,000.00","-1,000,000.00","-1,000,000.00",GBP,"-1,000,000.00",GBP,GBP,Balance,81088534,0.00,GBP,"-1,000,000.00",GBP,"-1,000,000.00",GBP,0.00,GBP,0.00,GBP,[],0.00,0.00

,instrument_scope,instrument_uid,SHK,instrument,holding_type,units,settled_units,cost.amount,cost.currency,cost_portfolio_ccy.amount,cost_portfolio_ccy.currency,currency,holding_type_name,holding_id,notional_cost.amount,notional_cost.currency,amortised_cost.amount,amortised_cost.currency,amortised_cost_portfolio_ccy.amount,amortised_cost_portfolio_ccy.currency,variation_margin.amount,variation_margin.currency,variation_margin_portfolio_ccy.amount,variation_margin_portfolio_ccy.currency,settlement_schedule,unsettled_units,overdue_units
0,FBNTutorialsFlexRepo,LUID_00003H1O,<Not Classified>,BondCollateral,P,3.00,3.00,0.00,GBP,0.00,GBP,GBP,Position,81088532,0.00,GBP,0.00,GBP,0.00,GBP,0.00,GBP,0.00,GBP,[],0.00,0.00
1,default,CCY_GBP,<Not Classified>,GBP,B,"12,054.79","12,054.79","12,054.79",GBP,"12,054.79",GBP,GBP,Balance,81088534,0.00,GBP,"12,054.79",GBP,"12,054.79",GBP,0.00,GBP,0.00,GBP,[],0.00,0.00
2,default,CCY_GBP,BondCollateralCoupons,GBP,B,187.50,187.50,187.50,GBP,187.50,GBP,GBP,Balance,81088535,0.00,GBP,187.50,GBP,187.50,GBP,0.00,GBP,0.00,GBP,[],0.00,0.00

Seller-Term

,instrument_scope,instrument_uid,SHK,instrument,holding_type,units,settled_units,cost.amount,cost.currency,cost_portfolio_ccy.amount,cost_portfolio_ccy.currency,currency,holding_type_name,holding_id,notional_cost.amount,notional_cost.currency,amortised_cost.amount,amortised_cost.currency,amortised_cost_portfolio_ccy.amount,amortised_cost_portfolio_ccy.currency,variation_margin.amount,variation_margin.currency,variation_margin_portfolio_ccy.amount,variation_margin_portfolio_ccy.currency,settlement_schedule,unsettled_units,overdue_units
0,FBNTutorialsFlexRepo,LUID_00003H1O,<Not Classified>,BondCollateral,P,3.00,3.00,0.00,GBP,0.00,GBP,GBP,Position,81088536,0.00,GBP,0.00,GBP,0.00,GBP,0.00,GBP,0.00,GBP,[],0.00,0.00
1,FBNTutorialsFlexRepo,LUID_00003H1Q,<Not Classified>,Seller-TermFlexRepo,P,1.00,1.00,"-1,000,000.00",GBP,"-1,000,000.00",GBP,GBP,Position,81088537,0.00,GBP,"-1,000,000.00",GBP,"-1,000,000.00",GBP,0.00,GBP,0.00,GBP,[],0.00,0.00
2,default,CCY_GBP,<Not Classified>,GBP,B,"1,000,000.00","1,000,000.00","1,000,000.00",GBP,"1,000,000.00",GBP,GBP,Balance,81088538,0.00,GBP,"1,000,000.00",GBP,"1,000,000.00",GBP,0.00,GBP,0.00,GBP,[],0.00,0.00

,instrument_scope,instrument_uid,SHK,instrument,holding_type,units,settled_units,cost.amount,cost.currency,cost_portfolio_ccy.amount,cost_portfolio_ccy.currency,currency,holding_type_name,holding_id,notional_cost.amount,notional_cost.currency,amortised_cost.amount,amortised_cost.currency,amortised_cost_portfolio_ccy.amount,amortised_cost_portfolio_ccy.currency,variation_margin.amount,variation_margin.currency,variation_margin_portfolio_ccy.amount,variation_margin_portfolio_ccy.currency,settlement_schedule,unsettled_units,overdue_units
0,FBNTutorialsFlexRepo,LUID_00003H1O,<Not Classified>,BondCollateral,P,2.00,2.00,0.00,GBP,0.00,GBP,GBP,Position,81088536,0.00,GBP,0.00,GBP,0.00,GBP,0.00,GBP,0.00,GBP,[],0.00,0.00
1,FBNTutorialsFlexRepo,LUID_00003H1Q,<Not Classified>,Seller-TermFlexRepo,P,1.00,1.00,"-1,000,000.00",GBP,"-1,000,000.00",GBP,GBP,Position,81088537,0.00,GBP,"-1,000,000.00",GBP,"-1,000,000.00",GBP,0.00,GBP,0.00,GBP,[],0.00,0.00
2,default,CCY_GBP,<Not Classified>,GBP,B,"1,000,000.00","1,000,000.00","1,000,000.00",GBP,"1,000,000.00",GBP,GBP,Balance,81088538,0.00,GBP,"1,000,000.00",GBP,"1,000,000.00",GBP,0.00,GBP,0.00,GBP,[],0.00,0.00

,instrument_scope,instrument_uid,SHK,instrument,holding_type,units,settled_units,cost.amount,cost.currency,cost_portfolio_ccy.amount,cost_portfolio_ccy.currency,currency,holding_type_name,holding_id,notional_cost.amount,notional_cost.currency,amortised_cost.amount,amortised_cost.currency,amortised_cost_portfolio_ccy.amount,amortised_cost_portfolio_ccy.currency,variation_margin.amount,variation_margin.currency,variation_margin_portfolio_ccy.amount,variation_margin_portfolio_ccy.currency,settlement_schedule,unsettled_units,overdue_units
0,FBNTutorialsFlexRepo,LUID_00003H1O,<Not Classified>,BondCollateral,P,3.00,3.00,0.00,GBP,0.00,GBP,GBP,Position,81088536,0.00,GBP,0.00,GBP,0.00,GBP,0.00,GBP,0.00,GBP,[],0.00,0.00
1,default,CCY_GBP,<Not Classified>,GBP,B,"-12,054.79","-12,054.79","-12,054.79",GBP,"-12,054.79",GBP,GBP,Balance,81088538,0.00,GBP,"-12,054.79",GBP,"-12,054.79",GBP,0.00,GBP,0.00,GBP,[],0.00,0.00
2,default,CCY_GBP,BondCollateralCoupons,GBP,B,187.50,187.50,187.50,GBP,187.50,GBP,GBP,Balance,81088539,0.00,GBP,187.50,GBP,187.50,GBP,0.00,GBP,0.00,GBP,[],0.00,0.00

In [39]:
for port in ports:
    print(f"\n{port}")
    get_output_transactions(port, "2025-01-01", "2025-06-01")

Buyer-Term

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
transaction_id,Txn01,Txn02,LUID_00003H1P_FlexibleRepoCollateralEvent_2025...,LUID_00003H1O_BondCouponEvent_20250128-81088532,LUID_00003H1O_BondCouponEvent_20250128-Manufac...,LUID_00003H1O_BondCouponEvent_20250228-81088532,LUID_00003H1O_BondCouponEvent_20250228-Manufac...,LUID_00003H1O_BondCouponEvent_20250328-81088532,LUID_00003H1O_BondCouponEvent_20250328-Manufac...,LUID_00003H1P_FlexibleRepoCashFlowEvent_2025-0...,LUID_00003H1P_FlexibleRepoCollateralEvent_2025...,LUID_00003H1P_FlexibleRepoInterestPaymentEvent...,LUID_00003H1P_MaturityEvent_20250331-81088533,LUID_00003H1O_BondCouponEvent_20250428-81088532,LUID_00003H1O_BondCouponEvent_20250528-81088532
type,StockIn,EnterRepo,FlexibleRepoCollateralTransfer,BondCoupon,BondCoupon,BondCoupon,BondCoupon,BondCoupon,BondCoupon,FlexibleRepoCashTransfer,FlexibleRepoCollateralTransfer,FlexibleRepoInterestPayment,Maturity,BondCoupon,BondCoupon
description,Transfer in,Open the contract,Transaction type for transactions automaticall...,Type for bond coupon event,Type for bond coupon event,Type for bond coupon event,Type for bond coupon event,Type for bond coupon event,Type for bond coupon event,Transaction type for transactions automaticall...,Transaction type for transactions automaticall...,Transaction type for transactions automaticall...,Type for maturity event for various instruments,Type for bond coupon event,Type for bond coupon event
instrument_identifiers.Instrument/default/LusidInstrumentId,LUID_00003H1O,LUID_00003H1P,LUID_00003H1O,LUID_00003H1O,LUID_00003H1P,LUID_00003H1O,LUID_00003H1P,LUID_00003H1O,LUID_00003H1P,LUID_00003H1P,LUID_00003H1O,LUID_00003H1P,LUID_00003H1P,LUID_00003H1O,LUID_00003H1O
instrument_scope,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo
instrument_uid,LUID_00003H1O,LUID_00003H1P,LUID_00003H1O,LUID_00003H1O,LUID_00003H1P,LUID_00003H1O,LUID_00003H1P,LUID_00003H1O,LUID_00003H1P,LUID_00003H1P,LUID_00003H1O,LUID_00003H1P,LUID_00003H1P,LUID_00003H1O,LUID_00003H1O
transaction_date,2025-01-01 00:00:00+00:00,2025-01-01 00:00:00+00:00,2025-01-02 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-04-28 00:00:00+00:00,2025-05-28 00:00:00+00:00
settlement_date,2025-01-01 00:00:00+00:00,2025-01-01 00:00:00+00:00,2025-01-02 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-04-28 00:00:00+00:00,2025-05-28 00:00:00+00:00
units,3.00,1.00,1.00,4.00,1.00,4.00,1.00,4.00,1.00,1.00,-1.00,1.00,1.00,3.00,3.00
transaction_amount,0.00,"1,000,000.00",0.00,83.33,20.83,83.33,20.83,83.33,20.83,"1,000,000.00",0.00,"12,054.79",0.00,62.50,62.50
transaction_price.price,0.00,0.00,0.00,20.83,-20.83,20.83,-20.83,20.83,-20.83,"1,000,000.00",0.00,"12,054.79",0.00,20.83,20.83
transaction_price.type,Price,Price,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,Price,CashFlowPerUnit,CashFlowPerUnit
total_consideration.amount,8.22,"-1,000,000.00",0.00,83.33,-20.83,83.33,-20.83,83.33,-20.83,"1,000,000.00",0.00,"12,054.79",0.00,62.50,62.50
total_consideration.currency,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP
exchange_rate,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
transaction_to_portfolio_rate,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
transaction_currency,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP
properties.Transaction/default/SourcePortfolioId.key,Transaction/default/SourcePortfolioId,Transaction/default/SourcePortfolioId,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.Transaction/default/SourcePortfolioId.value.label_value,FlexRepo-Buyer-Term,FlexRepo-Buyer-Term,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.Transaction/default/SourcePortfolioScope.key,Transaction/default/SourcePortfolioScope,Transaction/default/SourcePortfolioScope,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.Transaction/default/SourcePortfolioScope.value.label_value,FBNTutorials,FBNTutorials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.Transaction/default/GrossConsideration.key,Transaction/default/GrossConsideration,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.Transaction/default/GrossConsideration.value.metric_value.value,8.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.Transaction/default/BondInterest.key,Transaction/default/BondInterest,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.Transaction/default/BondInterest.value.metric_value.value,8.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.Transaction/default/ResultantHolding.key,Transaction/default/ResultantHolding,Transaction/default/ResultantHolding,Transaction/default/ResultantHolding,NaN,NaN,NaN,NaN,NaN,NaN,Transaction/default/ResultantHolding,Transaction/default/ResultantHolding,NaN,Transaction/default/ResultantHolding,NaN,NaN
properties.Transaction/default/ResultantHolding.value.metric_value.value,3.00,1.00,4.00,NaN,NaN,NaN,NaN,NaN,NaN,1.00,3.00,NaN,0.00,NaN,NaN
source,,,default,default,default,default,default,default,default,default,default,default,default,default,default
transaction_status,Active,Active,Active,Active,Active,Active,Active,Active,Active,Active,Active,Active,Active,Active,Active
entry_date_time,2026-06-10 11:45:46.589337+00:00,2026-06-10 11:45:47.636168+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00
realised_gain_loss,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]
holding_ids.0,81088532,81088533,81088532,81088535,81088535,81088535,81088535,81088535,81088535,81088534,81088532,81088534,81088533,81088535,81088535
source_type,InputTransaction,InputTransaction,InstrumentEvent,InstrumentEvent,InstrumentEvent,InstrumentEvent,InstrumentEvent,InstrumentEvent,InstrumentEvent,InstrumentEvent,InstrumentEvent,InstrumentEvent,InstrumentEvent,InstrumentEvent,InstrumentEvent
source_instrument_event_id,None,None,LUID_00003H1P_FlexibleRepoCollateralEvent_2025...,LUID_00003H1O_BondCouponEvent_20250128,LUID_00003H1O_BondCouponEvent_20250128-Manufac...,LUID_00003H1O_BondCouponEvent_20250228,LUID_00003H1O_BondCouponEvent_20250228-Manufac...,LUID_00003H1O_BondCouponEvent_20250328,LUID_00003H1O_BondCouponEvent_20250328-Manufac...,LUID_00003H1P_FlexibleRepoCashFlowEvent_2025-0...,LUID_00003H1P_FlexibleRepoCollateralEvent_2025...,LUID_00003H1P_FlexibleRepoInterestPaymentEvent...,LUID_00003H1P_MaturityEvent_20250331,LUID_00003H1O_BondCouponEvent_20250428,LUID_00003H1O_BondCouponEvent_20250528
transaction_group_id,None,None,LUID_00003H1P_FlexibleRepoCollateralEvent_2025...,LUID_00003H1O_BondCouponEvent_20250128,LUID_00003H1O_BondCouponEvent_20250128-Manufac...,LUID_00003H1O_BondCouponEvent_20250228,LUID_00003H1O_BondCouponEvent_20250228-Manufac...,LUID_00003H1O_BondCouponEvent_20250328,LUID_00003H1O_BondCouponEvent_20250328-Manufac...,LUID_00003H1P_FlexibleRepoCashFlowEvent_2025-0...,LUID_00003H1P_FlexibleRepoCollateralEvent_2025...,LUID_00003H1P_FlexibleRepoInterestPaymentEvent...,LUID_00003H1P_MaturityEvent_20250331,LUID_00003H1O_BondCouponEvent_20250428,LUID_00003H1O_BondCouponEvent_20250528
resolved_transaction_type_details.scope,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo
resolved_transaction_type_details.source,default,default,default,default,default,default,default,default,default,default,default,default,default,default,default
resolved_transaction_type_details.type,StockIn,EnterRepo,FlexibleRepoCollateralTransfer,BondCoupon,BondCoupon,BondCoupon,BondCoupon,BondCoupon,BondCoupon,FlexibleRepoCashTransfer,FlexibleRepoCollateralTransfer,FlexibleRepoInterestPayment,Maturity,BondCoupon,BondCoupon
gross_transaction_amount,0.00,0.00,0.00,"83,333.33","-20,833,333.33","83,333.33","-20,833,333.33","83,333.33","-20,833,333.33","1,000,000,000,000.00",0.00,"12,054,794,520.55",0.00,"62,500.00","62,500.00"
accounting_date,2025-01-01 00:00:00+00:00,2025-01-01 00:00:00+00:00,2025-01-02 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-04-28 00:00:00+00:00,2025-05-28 00:00:00+00:00
economics,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]
data_model_membership.membership,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]
sequence,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
version.effective_from,2025-01-01 00:00:00+00:00,2025-01-01 00:00:00+00:00,2025-01-02 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-04-28 00:00:00+00:00,2025-05-28 00:00:00+00:00
version.as_at_date,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00
version.entity_unique_id,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000
holding_ids.1,NaN,"81,088,534.00",NaN,"81,088,532.00","81,088,533.00","81,088,532.00","81,088,533.00","81,088,532.00","81,088,533.00","81,088,533.00",NaN,"81,088,533.00",NaN,"81,088,532.00","81,088,532.00"
properties.Transaction/SHKs/BondCollateralCoupons.key,NaN,NaN,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons
properties.Transaction/SHKs/BondCollateralCoupons.value.label_value,NaN,NaN,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>
properties.Transaction/system/OverrideOfInstrumentEvent.key,NaN,NaN,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent
properties.Transaction/system/OverrideOfInstrumentEvent.value.label_value,NaN,NaN,LUID_00003H1P_FlexibleRepoCollateralEvent_2025...,LUID_00003H1O_BondCouponEvent_20250128,LUID_00003H1O_BondCouponEvent_20250128-Manufac...,LUID_00003H1O_BondCouponEvent_20250228,LUID_00003H1O_BondCouponEvent_20250228-Manufac...,LUID_00003H1O_BondCouponEvent_20250328,LUID_00003H1O_BondCouponEvent_20250328-Manufac...,LUID_00003H1P_FlexibleRepoCashFlowEvent_2025-0...,LUID_00003H1P_FlexibleRepoCollateralEvent_2025...,LUID_00003H1P_FlexibleRepoInterestPaymentEvent...,LUID_00003H1P_MaturityEvent_20250331,LUID_00003H1O_BondCouponEvent_20250428,LUID_00003H1O_BondCouponEvent_20250528

Seller-Term

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
transaction_id,Txn01,Txn02,LUID_00003H1Q_FlexibleRepoCollateralEvent_2025...,LUID_00003H1O_BondCouponEvent_20250128-81088536,LUID_00003H1O_BondCouponEvent_20250128-Manufac...,LUID_00003H1O_BondCouponEvent_20250228-81088536,LUID_00003H1O_BondCouponEvent_20250228-Manufac...,LUID_00003H1O_BondCouponEvent_20250328-81088536,LUID_00003H1O_BondCouponEvent_20250328-Manufac...,LUID_00003H1Q_FlexibleRepoCashFlowEvent_2025-0...,LUID_00003H1Q_FlexibleRepoCollateralEvent_2025...,LUID_00003H1Q_FlexibleRepoInterestPaymentEvent...,LUID_00003H1Q_MaturityEvent_20250331-81088537,LUID_00003H1O_BondCouponEvent_20250428-81088536,LUID_00003H1O_BondCouponEvent_20250528-81088536
type,StockIn,EnterRepo,FlexibleRepoCollateralTransfer,BondCoupon,BondCoupon,BondCoupon,BondCoupon,BondCoupon,BondCoupon,FlexibleRepoCashTransfer,FlexibleRepoCollateralTransfer,FlexibleRepoInterestPayment,Maturity,BondCoupon,BondCoupon
description,Transfer in,Open the contract,Transaction type for transactions automaticall...,Type for bond coupon event,Type for bond coupon event,Type for bond coupon event,Type for bond coupon event,Type for bond coupon event,Type for bond coupon event,Transaction type for transactions automaticall...,Transaction type for transactions automaticall...,Transaction type for transactions automaticall...,Type for maturity event for various instruments,Type for bond coupon event,Type for bond coupon event
instrument_identifiers.Instrument/default/LusidInstrumentId,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1O
instrument_scope,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo
instrument_uid,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1O
transaction_date,2025-01-01 00:00:00+00:00,2025-01-01 00:00:00+00:00,2025-01-02 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-04-28 00:00:00+00:00,2025-05-28 00:00:00+00:00
settlement_date,2025-01-01 00:00:00+00:00,2025-01-01 00:00:00+00:00,2025-01-02 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-04-28 00:00:00+00:00,2025-05-28 00:00:00+00:00
units,3.00,1.00,-1.00,2.00,1.00,2.00,1.00,2.00,1.00,1.00,1.00,1.00,1.00,3.00,3.00
transaction_amount,0.00,"1,000,000.00",0.00,41.67,20.83,41.67,20.83,41.67,20.83,"1,000,000.00",0.00,"12,054.79",0.00,62.50,62.50
transaction_price.price,0.00,0.00,0.00,20.83,20.83,20.83,20.83,20.83,20.83,"-1,000,000.00",0.00,"-12,054.79",0.00,20.83,20.83
transaction_price.type,Price,Price,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,Price,CashFlowPerUnit,CashFlowPerUnit
total_consideration.amount,8.22,"1,000,000.00",0.00,41.67,20.83,41.67,20.83,41.67,20.83,"-1,000,000.00",0.00,"-12,054.79",0.00,62.50,62.50
total_consideration.currency,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP
exchange_rate,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
transaction_to_portfolio_rate,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
transaction_currency,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP
properties.Transaction/default/SourcePortfolioId.key,Transaction/default/SourcePortfolioId,Transaction/default/SourcePortfolioId,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.Transaction/default/SourcePortfolioId.value.label_value,FlexRepo-Seller-Term,FlexRepo-Seller-Term,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.Transaction/default/SourcePortfolioScope.key,Transaction/default/SourcePortfolioScope,Transaction/default/SourcePortfolioScope,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.Transaction/default/SourcePortfolioScope.value.label_value,FBNTutorials,FBNTutorials,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.Transaction/default/GrossConsideration.key,Transaction/default/GrossConsideration,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.Transaction/default/GrossConsideration.value.metric_value.value,8.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.Transaction/default/BondInterest.key,Transaction/default/BondInterest,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.Transaction/default/BondInterest.value.metric_value.value,8.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
properties.Transaction/default/ResultantHolding.key,Transaction/default/ResultantHolding,Transaction/default/ResultantHolding,Transaction/default/ResultantHolding,NaN,NaN,NaN,NaN,NaN,NaN,Transaction/default/ResultantHolding,Transaction/default/ResultantHolding,NaN,Transaction/default/ResultantHolding,NaN,NaN
properties.Transaction/default/ResultantHolding.value.metric_value.value,3.00,1.00,2.00,NaN,NaN,NaN,NaN,NaN,NaN,1.00,3.00,NaN,0.00,NaN,NaN
source,,,default,default,default,default,default,default,default,default,default,default,default,default,default
transaction_status,Active,Active,Active,Active,Active,Active,Active,Active,Active,Active,Active,Active,Active,Active,Active
entry_date_time,2026-06-10 11:45:47.149621+00:00,2026-06-10 11:45:48.266549+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00
realised_gain_loss,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]
holding_ids.0,81088536,81088537,81088536,81088539,81088539,81088539,81088539,81088539,81088539,81088538,81088536,81088538,81088537,81088539,81088539
source_type,InputTransaction,InputTransaction,InstrumentEvent,InstrumentEvent,InstrumentEvent,InstrumentEvent,InstrumentEvent,InstrumentEvent,InstrumentEvent,InstrumentEvent,InstrumentEvent,InstrumentEvent,InstrumentEvent,InstrumentEvent,InstrumentEvent
source_instrument_event_id,None,None,LUID_00003H1Q_FlexibleRepoCollateralEvent_2025...,LUID_00003H1O_BondCouponEvent_20250128,LUID_00003H1O_BondCouponEvent_20250128-Manufac...,LUID_00003H1O_BondCouponEvent_20250228,LUID_00003H1O_BondCouponEvent_20250228-Manufac...,LUID_00003H1O_BondCouponEvent_20250328,LUID_00003H1O_BondCouponEvent_20250328-Manufac...,LUID_00003H1Q_FlexibleRepoCashFlowEvent_2025-0...,LUID_00003H1Q_FlexibleRepoCollateralEvent_2025...,LUID_00003H1Q_FlexibleRepoInterestPaymentEvent...,LUID_00003H1Q_MaturityEvent_20250331,LUID_00003H1O_BondCouponEvent_20250428,LUID_00003H1O_BondCouponEvent_20250528
transaction_group_id,None,None,LUID_00003H1Q_FlexibleRepoCollateralEvent_2025...,LUID_00003H1O_BondCouponEvent_20250128,LUID_00003H1O_BondCouponEvent_20250128-Manufac...,LUID_00003H1O_BondCouponEvent_20250228,LUID_00003H1O_BondCouponEvent_20250228-Manufac...,LUID_00003H1O_BondCouponEvent_20250328,LUID_00003H1O_BondCouponEvent_20250328-Manufac...,LUID_00003H1Q_FlexibleRepoCashFlowEvent_2025-0...,LUID_00003H1Q_FlexibleRepoCollateralEvent_2025...,LUID_00003H1Q_FlexibleRepoInterestPaymentEvent...,LUID_00003H1Q_MaturityEvent_20250331,LUID_00003H1O_BondCouponEvent_20250428,LUID_00003H1O_BondCouponEvent_20250528
resolved_transaction_type_details.scope,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo
resolved_transaction_type_details.source,default,default,default,default,default,default,default,default,default,default,default,default,default,default,default
resolved_transaction_type_details.type,StockIn,EnterRepo,FlexibleRepoCollateralTransfer,BondCoupon,BondCoupon,BondCoupon,BondCoupon,BondCoupon,BondCoupon,FlexibleRepoCashTransfer,FlexibleRepoCollateralTransfer,FlexibleRepoInterestPayment,Maturity,BondCoupon,BondCoupon
gross_transaction_amount,0.00,0.00,0.00,"41,666.67","-20,833,333.33","41,666.67","-20,833,333.33","41,666.67","-20,833,333.33","1,000,000,000,000.00",0.00,"12,054,794,520.55",0.00,"62,500.00","62,500.00"
accounting_date,2025-01-01 00:00:00+00:00,2025-01-01 00:00:00+00:00,2025-01-02 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-04-28 00:00:00+00:00,2025-05-28 00:00:00+00:00
economics,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]
data_model_membership.membership,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]
sequence,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
version.effective_from,2025-01-01 00:00:00+00:00,2025-01-01 00:00:00+00:00,2025-01-02 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-04-28 00:00:00+00:00,2025-05-28 00:00:00+00:00
version.as_at_date,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00,2026-06-10 11:45:55.337996+00:00
version.entity_unique_id,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000
holding_ids.1,NaN,"81,088,538.00",NaN,"81,088,536.00","81,088,537.00","81,088,536.00","81,088,537.00","81,088,536.00","81,088,537.00","81,088,537.00",NaN,"81,088,537.00",NaN,"81,088,536.00","81,088,536.00"
properties.Transaction/SHKs/BondCollateralCoupons.key,NaN,NaN,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons
properties.Transaction/SHKs/BondCollateralCoupons.value.label_value,NaN,NaN,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>
properties.Transaction/system/OverrideOfInstrumentEvent.key,NaN,NaN,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent
properties.Transaction/system/OverrideOfInstrumentEvent.value.label_value,NaN,NaN,LUID_00003H1Q_FlexibleRepoCollateralEvent_2025...,LUID_00003H1O_BondCouponEvent_20250128,LUID_00003H1O_BondCouponEvent_20250128-Manufac...,LUID_00003H1O_BondCouponEvent_20250228,LUID_00003H1O_BondCouponEvent_20250228-Manufac...,LUID_00003H1O_BondCouponEvent_20250328,LUID_00003H1O_BondCouponEvent_20250328-Manufac...,LUID_00003H1Q_FlexibleRepoCashFlowEvent_2025-0...,LUID_00003H1Q_FlexibleRepoCollateralEvent_2025...,LUID_00003H1Q_FlexibleRepoInterestPaymentEvent...,LUID_00003H1Q_MaturityEvent_20250331,LUID_00003H1O_BondCouponEvent_20250428,LUID_00003H1O_BondCouponEvent_20250528

## Valuation

See https://support.lusid.com/docs/modelling-repurchase-agreements-in-lusid#valuing-your-position.

### Load market data

Using `FlexibleRepoSimplePricer`, there is no need to load market prices for `FlexibleRepo` instruments. Only market prices for the collateral instrument (in this case, `Bond`) required.

In [40]:
def load_quotes(luid, price, date, ccy, scale):
    if date == "today":
        date = str(datetime.datetime.now().replace(microsecond=0))

    quotes = {
        # Each quote must be upserted with an ephemeral key (uuid in this case), to track errors in the response
        str(uuid.uuid4()): lm.UpsertQuoteRequest(
            quote_id = lm.QuoteId(
                quote_series_id = lm.QuoteSeriesId(
                    # Must be one of the valid financial data vendor 'provider' values
                    provider = "Lusid",
                    instrument_id_type = "LusidInstrumentId",
                    instrument_id = luid,
                    quote_type = "Price",
                    # Case sensitive: the field value must match that of the equivalent recipe field exactly
                    field = "mid",
                ),
                effective_at = datetime.strptime(date, '%Y-%m-%d %H:%M:%S').replace(tzinfo=timezone.utc).isoformat(),
            ),
            metric_value = lm.MetricValue(value = price, unit = ccy),
            scale_factor = scale,
        )
    }

    try:
        upsert_quotes_response = quotes_api.upsert_quotes(scope = f"{module_scope}{module_code}", request_body = quotes)    
        if upsert_quotes_response.failed == {}:
            print(f"Price for {date} successfully loaded into LUSID.")
        else:
            print(f"Some failures occurred. {len(upsert_quotes_response.failed)} prices did not get loaded into LUSID.")
    except ApiException as e:
        print(e)

In [41]:
load_quotes(luid_dict["BondCollateral"], 100, "2025-01-01 00:00:00", "GBP", 100) # Transaction date (required to calculate YTD P&L)
load_quotes(luid_dict["BondCollateral"], 101, "2025-02-14 00:00:00", "GBP", 100) # Random valuation date

Price for 2025-01-01 00:00:00 successfully loaded into LUSID.
Price for 2025-02-14 00:00:00 successfully loaded into LUSID.

In [42]:
def list_quotes():
    try:
        quotes_response = quotes_api.list_quotes_for_scope(f"{module_scope}{module_code}")
        quotes_response_df = lusid_response_to_data_frame(quotes_response)
        display(quotes_response_df)        
    except ApiException as e:
        print(e)

list_quotes()

,quote_id.quote_series_id.provider,quote_id.quote_series_id.instrument_id,quote_id.quote_series_id.instrument_id_type,quote_id.quote_series_id.quote_type,quote_id.quote_series_id.var_field,quote_id.quote_series_id.entity_unique_id,quote_id.effective_at,metric_value.value,metric_value.unit,lineage,cut_label,uploaded_by,as_at,scale_factor
0,Lusid,LUID_00003H1O,LusidInstrumentId,Price,mid,e1c303f7-563f-4d08-81ca-d0946dc56637,2025-02-14T00:00:00.0000000+00:00,101.00,GBP,,,00u91lo2d7X42sdse2p7,2026-06-10 11:45:58.042026+00:00,100.00
1,Lusid,LUID_00003H1O,LusidInstrumentId,Price,mid,e1c303f7-563f-4d08-81ca-d0946dc56637,2025-01-01T00:00:00.0000000+00:00,100.00,GBP,,,00u91lo2d7X42sdse2p7,2026-06-10 11:45:57.855914+00:00,100.00

In [43]:
def value_instruments(port, date, pnl_window):
    if date == "today":
        date = str(datetime.now().replace(microsecond=0))

    valuation_request = lm.ValuationRequest(
        # Choose recipe to use
        recipe_id = lm.ResourceId(scope = module_scope, code = f"{module_code}-FlexibleRepoSimplePricer"),
        # Specify metrics (also known as queryable keys) to report useful information
        metrics = [
            lm.AggregateSpec(key="Instrument/InstrumentCategory", op="Value"),
            lm.AggregateSpec(key="Valuation/Model/Name", op="Value"),
            lm.AggregateSpec(key="Instrument/default/LusidInstrumentId", op="Value"),
            lm.AggregateSpec(key="Instrument/default/Name", op="Value"),
            lm.AggregateSpec(key="Valuation/EffectiveAt", op="Value"),
            lm.AggregateSpec(key="Holding/default/Units", op="Value"),
            lm.AggregateSpec(key="Quotes/PriceOrFXRate", op="Value"),
            lm.AggregateSpec(key="Holding/Cost/Dom", op="Value"),
            lm.AggregateSpec(key="Valuation/CleanPV", op="Value"),
            lm.AggregateSpec(key="Valuation/PV", op="Value"),
            lm.AggregateSpec(key="Valuation/Accrued", op="Value"),
            lm.AggregateSpec(key="Valuation/Exposure", op="Value"),
            lm.AggregateSpec(key="Valuation/CurrentNotional", op="Value"), 
            lm.AggregateSpec(key="ProfitAndLoss/Total", op="Value", options={"Window": f"{pnl_window}"}),      
            lm.AggregateSpec(key="ProfitAndLoss/Total/Market", op="Value", options={"Window": f"{pnl_window}"}),
            lm.AggregateSpec(key="ProfitAndLoss/Realised/Market", op="Value", options={"Window": f"{pnl_window}"}),       
            lm.AggregateSpec(key="ProfitAndLoss/Unrealised/Market", op="Value", options={"Window": f"{pnl_window}"}),       
            lm.AggregateSpec(key="ProfitAndLoss/Total/Other", op="Value", options={"Window": f"{pnl_window}"}),
            lm.AggregateSpec(key="Aggregation/Errors", op="Value"), 
        ],
        # Identify portfolio to value
        portfolio_entity_ids = [lm.PortfolioEntityId(scope = module_scope, code = f"{module_code}-{port}")],
        valuation_schedule = lm.ValuationSchedule(effective_at = date),

    )

    try:
        # Get portfolio valuation
        val_response = aggregation_api.get_valuation(valuation_request = valuation_request)
        val_response_df = pd.json_normalize(val_response.to_dict()["data"], sep='.')
        # Rename columns
        val_response_df.rename(
            columns = {
                "Instrument/InstrumentCategory": "Category",
                "Valuation/Model/Name": "Model",
                "Instrument/default/LusidInstrumentId": "LUID",
                "Instrument/default/Name": "Name",
                "Valuation/EffectiveAt": "Date",
                "Holding/default/Units": "Units",
                "Quotes/PriceOrFXRate": "Price",
                "Quotes/ScaleFactor": "Quote Scale Factor",
                "Holding/Cost/Dom": "Local Cost",
                "Valuation/CleanPV": "Local Clean PV",
                "Valuation/PV": "Local PV",
                "Valuation/Accrued": "Local Accrued Interest",
                "Valuation/Exposure": "Exposure",
                "Valuation/CurrentNotional": "Notional",            
                f"ProfitAndLoss/Total(Window=\"{pnl_window}\")": "Total P&L",
                f"ProfitAndLoss/Total/Market(Window=\"{pnl_window}\")": "Total/Market P&L",
                f"ProfitAndLoss/Realised/Market(Window=\"{pnl_window}\")": "Realised/Market P&L",
                f"ProfitAndLoss/Unrealised/Market(Window=\"{pnl_window}\")": "Unrealised/Market P&L",
                f"ProfitAndLoss/Total/Other(Window=\"{pnl_window}\")": "Total/Other P&L",
                "Aggregation/Errors": "Errors"
            },
            inplace = True,
        )
    #     #val_each_instrument_df["Date"] = pd.to_datetime(val_each_instrument_df["Date"]).dt.date
        display(val_response_df)
    except ApiException as e:
        print(e)

In [44]:
for port in ports:
    print(port)
    value_instruments(port, "2025-02-15T17:00:00Z", "YTD") # Random valuation date

Buyer-Term

,Category,Model,LUID,Name,Date,Units,Price,Local Cost,Local Clean PV,Local PV,Local Accrued Interest,Exposure,Notional,Total P&L,Total/Market P&L,Realised/Market P&L,Unrealised/Market P&L,Total/Other P&L,Errors
0,Bond,BondLookupPricer,LUID_00003H1O,BondCollateral,2025-02-15T17:00:00.0000000+00:00,4.00,101.00,0.00,"4,040.00","4,092.05",52.05,"4,092.05","1,000.00","4,175.38","4,040.00",0.00,"4,040.00",135.38,[]
1,FlexibleRepo,FlexibleRepoSimplePricer,LUID_00003H1P,Buyer-TermFlexRepo,2025-02-15T17:00:00.0000000+00:00,1.00,1.00,"1,000,000.00","1,000,000.00","1,006,164.38","6,164.38","1,100,000.00","1,000,000.00","6,185.21",-0.00,0.00,-0.00,"6,185.21",[]
2,Cash,ConstantTimeValueOfMoney,CCY_GBP,GBP,2025-02-15T17:00:00.0000000+00:00,"-1,000,000.00",1.00,"-1,000,000.00","-1,000,000.00","-1,000,000.00",0.00,"-1,000,000.00",1.00,0.00,0.00,0.00,0.00,0.00,[]
3,Cash,ConstantTimeValueOfMoney,CCY_GBP,GBP,2025-02-15T17:00:00.0000000+00:00,62.50,1.00,62.50,62.50,62.50,0.00,62.50,1.00,0.00,0.00,0.00,0.00,0.00,[]

Seller-Term

,Category,Model,LUID,Name,Date,Units,Price,Local Cost,Local Clean PV,Local PV,Local Accrued Interest,Exposure,Notional,Total P&L,Total/Market P&L,Realised/Market P&L,Unrealised/Market P&L,Total/Other P&L,Errors
0,Bond,BondLookupPricer,LUID_00003H1O,BondCollateral,2025-02-15T17:00:00.0000000+00:00,2.00,101.00,0.00,"2,020.00","2,046.03",26.03,"2,046.03","1,000.00","2,087.70","2,020.00",0.00,"2,020.00",67.70,[]
1,FlexibleRepo,FlexibleRepoSimplePricer,LUID_00003H1Q,Seller-TermFlexRepo,2025-02-15T17:00:00.0000000+00:00,1.00,1.00,"-1,000,000.00","-1,000,000.00","-1,006,164.38","-6,164.38","-1,100,000.00","-1,000,000.00","-6,143.55",0.00,0.00,0.00,"-6,143.55",[]
2,Cash,ConstantTimeValueOfMoney,CCY_GBP,GBP,2025-02-15T17:00:00.0000000+00:00,"1,000,000.00",1.00,"1,000,000.00","1,000,000.00","1,000,000.00",0.00,"1,000,000.00",1.00,0.00,0.00,0.00,0.00,0.00,[]
3,Cash,ConstantTimeValueOfMoney,CCY_GBP,GBP,2025-02-15T17:00:00.0000000+00:00,62.50,1.00,62.50,62.50,62.50,0.00,62.50,1.00,0.00,0.00,0.00,0.00,0.00,[]

## Check instrument events that generated output transactions

In [45]:
def query_instr_events(port):
    
    query_id_request = lm.QueryApplicableInstrumentEventsRequest(
        window_start = datetime.strptime("2015-01-01", '%Y-%m-%d').replace(tzinfo=timezone.utc).isoformat(),
        window_end = datetime.strptime("2025-05-31", '%Y-%m-%d').replace(tzinfo=timezone.utc).isoformat(),
        effective_at = datetime.strptime("2025-03-31", '%Y-%m-%d').replace(tzinfo=timezone.utc).isoformat(),
        portfolio_entity_ids = [
            lm.PortfolioEntityId(
                scope = module_scope,
                code = f"{module_code}-{port}",
            )
        ],
        forecasting_recipe_id = lm.ResourceId(
            scope = module_scope,
            code = f"{module_code}-FlexibleRepoSimplePricer"
        )
    )
    
    try:
        query_id_response = instrument_events_api.query_applicable_instrument_events(
            query_applicable_instrument_events_request = query_id_request,
            limit = 200
        )
        display(lusid_response_to_data_frame(query_id_response).transpose())
    except ApiException as e:
        print(e)

In [46]:
for port in ports:
    print(port)
    query_instr_events(port)

Buyer-Term

,0,1,2,3,4,5,6,7,8,9,10,11,12
portfolio_id.scope,FBNTutorials,FBNTutorials,FBNTutorials,FBNTutorials,FBNTutorials,FBNTutorials,FBNTutorials,FBNTutorials,FBNTutorials,FBNTutorials,FBNTutorials,FBNTutorials,FBNTutorials
portfolio_id.code,FlexRepo-Buyer-Term,FlexRepo-Buyer-Term,FlexRepo-Buyer-Term,FlexRepo-Buyer-Term,FlexRepo-Buyer-Term,FlexRepo-Buyer-Term,FlexRepo-Buyer-Term,FlexRepo-Buyer-Term,FlexRepo-Buyer-Term,FlexRepo-Buyer-Term,FlexRepo-Buyer-Term,FlexRepo-Buyer-Term,FlexRepo-Buyer-Term
holding_id,81088533,81088532,81088533,81088532,81088533,81088532,81088533,81088533,81088533,81088533,81088533,81088532,81088532
lusid_instrument_id,LUID_00003H1P,LUID_00003H1O,LUID_00003H1P,LUID_00003H1O,LUID_00003H1P,LUID_00003H1O,LUID_00003H1P,LUID_00003H1P,LUID_00003H1P,LUID_00003H1P,LUID_00003H1P,LUID_00003H1O,LUID_00003H1O
instrument_scope,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo
instrument_type,FlexibleRepo,Bond,FlexibleRepo,Bond,FlexibleRepo,Bond,FlexibleRepo,FlexibleRepo,FlexibleRepo,FlexibleRepo,FlexibleRepo,Bond,Bond
instrument_event_type,FlexibleRepoCollateralEvent,BondCouponEvent,BondCouponEvent,BondCouponEvent,BondCouponEvent,BondCouponEvent,BondCouponEvent,FlexibleRepoCashFlowEvent,FlexibleRepoCollateralEvent,FlexibleRepoInterestPaymentEvent,MaturityEvent,BondCouponEvent,BondCouponEvent
instrument_event_id,LUID_00003H1P_FlexibleRepoCollateralEvent_2025...,LUID_00003H1O_BondCouponEvent_20250128,LUID_00003H1O_BondCouponEvent_20250128-Manufac...,LUID_00003H1O_BondCouponEvent_20250228,LUID_00003H1O_BondCouponEvent_20250228-Manufac...,LUID_00003H1O_BondCouponEvent_20250328,LUID_00003H1O_BondCouponEvent_20250328-Manufac...,LUID_00003H1P_FlexibleRepoCashFlowEvent_2025-0...,LUID_00003H1P_FlexibleRepoCollateralEvent_2025...,LUID_00003H1P_FlexibleRepoInterestPaymentEvent...,LUID_00003H1P_MaturityEvent_20250331,LUID_00003H1O_BondCouponEvent_20250428,LUID_00003H1O_BondCouponEvent_20250528
generated_event.instrument_event_id,LUID_00003H1P_FlexibleRepoCollateralEvent_2025...,LUID_00003H1O_BondCouponEvent_20250128,LUID_00003H1O_BondCouponEvent_20250128-Manufac...,LUID_00003H1O_BondCouponEvent_20250228,LUID_00003H1O_BondCouponEvent_20250228-Manufac...,LUID_00003H1O_BondCouponEvent_20250328,LUID_00003H1O_BondCouponEvent_20250328-Manufac...,LUID_00003H1P_FlexibleRepoCashFlowEvent_2025-0...,LUID_00003H1P_FlexibleRepoCollateralEvent_2025...,LUID_00003H1P_FlexibleRepoInterestPaymentEvent...,LUID_00003H1P_MaturityEvent_20250331,LUID_00003H1O_BondCouponEvent_20250428,LUID_00003H1O_BondCouponEvent_20250528
generated_event.instrument_identifiers.Instrument/default/ClientInternal,Buyer-TermFlexRepo,BondCollateral,Buyer-TermFlexRepo,BondCollateral,Buyer-TermFlexRepo,BondCollateral,Buyer-TermFlexRepo,Buyer-TermFlexRepo,Buyer-TermFlexRepo,Buyer-TermFlexRepo,Buyer-TermFlexRepo,BondCollateral,BondCollateral
generated_event.lusid_instrument_id,LUID_00003H1P,LUID_00003H1O,LUID_00003H1P,LUID_00003H1O,LUID_00003H1P,LUID_00003H1O,LUID_00003H1P,LUID_00003H1P,LUID_00003H1P,LUID_00003H1P,LUID_00003H1P,LUID_00003H1O,LUID_00003H1O
generated_event.instrument_scope,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo
generated_event.description,Queried External Instrument Event of Type Flex...,Queried External Instrument Event of Type Bond...,Queried External Instrument Event of Type Bond...,Queried External Instrument Event of Type Bond...,Queried External Instrument Event of Type Bond...,Queried External Instrument Event of Type Bond...,Queried External Instrument Event of Type Bond...,Queried External Instrument Event of Type Flex...,Queried External Instrument Event of Type Flex...,Queried External Instrument Event of Type Flex...,Queried External Instrument Event of Type Matu...,Queried External Instrument Event of Type Bond...,Queried External Instrument Event of Type Bond...
generated_event.event_date_range.start,2025-01-02 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-04-28 00:00:00+00:00,2025-05-28 00:00:00+00:00
generated_event.event_date_range.end,2025-01-02 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-04-28 00:00:00+00:00,2025-05-28 00:00:00+00:00
generated_event.completeness,Complete,Complete,Complete,Complete,Complete,Complete,Complete,Complete,Complete,Complete,Complete,Complete,Complete
generated_event.instrument_event.instrument_event_type,FlexibleRepoCollateralEvent,BondCouponEvent,BondCouponEvent,BondCouponEvent,BondCouponEvent,BondCouponEvent,BondCouponEvent,FlexibleRepoCashFlowEvent,FlexibleRepoCollateralEvent,FlexibleRepoInterestPaymentEvent,MaturityEvent,BondCouponEvent,BondCouponEvent
generated_event.properties,[],[],[],[],[],[],[],[],[],[],[],[],[]
generated_event.sequence_number,20,20,20,20,20,20,20,20,20,30,1000,20,20
generated_event.participation_type,Mandatory,Mandatory,Mandatory,Mandatory,Mandatory,Mandatory,Mandatory,Mandatory,Mandatory,Mandatory,Mandatory,Mandatory,Mandatory
generated_event.group_code,Tier2,Tier3,Tier3,Tier3,Tier3,Tier3,Tier3,Tier2,Tier2,Tier2,Tier3,Tier3,Tier3
transactions.0.transaction_id,LUID_00003H1P_FlexibleRepoCollateralEvent_2025...,LUID_00003H1O_BondCouponEvent_20250128-81088532,LUID_00003H1O_BondCouponEvent_20250128-Manufac...,LUID_00003H1O_BondCouponEvent_20250228-81088532,LUID_00003H1O_BondCouponEvent_20250228-Manufac...,LUID_00003H1O_BondCouponEvent_20250328-81088532,LUID_00003H1O_BondCouponEvent_20250328-Manufac...,LUID_00003H1P_FlexibleRepoCashFlowEvent_2025-0...,LUID_00003H1P_FlexibleRepoCollateralEvent_2025...,LUID_00003H1P_FlexibleRepoInterestPaymentEvent...,LUID_00003H1P_MaturityEvent_20250331-81088533,LUID_00003H1O_BondCouponEvent_20250428-81088532,LUID_00003H1O_BondCouponEvent_20250528-81088532
transactions.0.type,FlexibleRepoCollateralTransfer,BondCoupon,BondCoupon,BondCoupon,BondCoupon,BondCoupon,BondCoupon,FlexibleRepoCashTransfer,FlexibleRepoCollateralTransfer,FlexibleRepoInterestPayment,Maturity,BondCoupon,BondCoupon
transactions.0.instrument_identifiers.Instrument/default/LusidInstrumentId,LUID_00003H1O,LUID_00003H1O,LUID_00003H1P,LUID_00003H1O,LUID_00003H1P,LUID_00003H1O,LUID_00003H1P,LUID_00003H1P,LUID_00003H1O,LUID_00003H1P,LUID_00003H1P,LUID_00003H1O,LUID_00003H1O
transactions.0.instrument_scope,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo
transactions.0.instrument_uid,LUID_00003H1O,LUID_00003H1O,LUID_00003H1P,LUID_00003H1O,LUID_00003H1P,LUID_00003H1O,LUID_00003H1P,LUID_00003H1P,LUID_00003H1O,LUID_00003H1P,LUID_00003H1P,LUID_00003H1O,LUID_00003H1O
transactions.0.transaction_date,2025-01-02 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-04-28 00:00:00+00:00,2025-05-28 00:00:00+00:00
transactions.0.settlement_date,2025-01-02 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-04-28 00:00:00+00:00,2025-05-28 00:00:00+00:00
transactions.0.units,1.00,4.00,1.00,4.00,1.00,4.00,1.00,1.00,-1.00,1.00,1.00,3.00,3.00
transactions.0.transaction_price.price,0.00,20.83,-20.83,20.83,-20.83,20.83,-20.83,"1,000,000.00",0.00,"12,054.79",0.00,20.83,20.83
transactions.0.transaction_price.type,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,Price,CashFlowPerUnit,CashFlowPerUnit
transactions.0.total_consideration.amount,0.00,83.33,-20.83,83.33,-20.83,83.33,-20.83,"1,000,000.00",0.00,"12,054.79",0.00,62.50,62.50
transactions.0.total_consideration.currency,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP
transactions.0.exchange_rate,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
transactions.0.transaction_currency,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP
transactions.0.properties.Transaction/SHKs/BondCollateralCoupons.key,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons
transactions.0.properties.Transaction/SHKs/BondCollateralCoupons.value.label_value,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>
transactions.0.properties.Transaction/system/OverrideOfInstrumentEvent.key,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent
transactions.0.properties.Transaction/system/OverrideOfInstrumentEvent.value.label_value,LUID_00003H1P_FlexibleRepoCollateralEvent_2025...,LUID_00003H1O_BondCouponEvent_20250128,LUID_00003H1O_BondCouponEvent_20250128-Manufac...,LUID_00003H1O_BondCouponEvent_20250228,LUID_00003H1O_BondCouponEvent_20250228-Manufac...,LUID_00003H1O_BondCouponEvent_20250328,LUID_00003H1O_BondCouponEvent_20250328-Manufac...,LUID_00003H1P_FlexibleRepoCashFlowEvent_2025-0...,LUID_00003H1P_FlexibleRepoCollateralEvent_2025...,LUID_00003H1P_FlexibleRepoInterestPaymentEvent...,LUID_00003H1P_MaturityEvent_20250331,LUID_00003H1O_BondCouponEvent_20250428,LUID_00003H1O_BondCouponEvent_20250528
transactions.0.source,default,default,default,default,default,default,default,default,default,default,default,default,default
transactions.0.entry_date_time,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00
transactions.0.transaction_status,Active,Active,Active,Active,Active,Active,Active,Active,Active,Active,Active,Active,Active
transactions.0.transaction_group_id,LUID_00003H1P_FlexibleRepoCollateralEvent_2025...,LUID_00003H1O_BondCouponEvent_20250128,LUID_00003H1O_BondCouponEvent_20250128-Manufac...,LUID_00003H1O_BondCouponEvent_20250228,LUID_00003H1O_BondCouponEvent_20250228-Manufac...,LUID_00003H1O_BondCouponEvent_20250328,LUID_00003H1O_BondCouponEvent_20250328-Manufac...,LUID_00003H1P_FlexibleRepoCashFlowEvent_2025-0...,LUID_00003H1P_FlexibleRepoCollateralEvent_2025...,LUID_00003H1P_FlexibleRepoInterestPaymentEvent...,LUID_00003H1P_MaturityEvent_20250331,LUID_00003H1O_BondCouponEvent_20250428,LUID_00003H1O_BondCouponEvent_20250528
transactions.0.resolved_transaction_type_details.scope,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo
transactions.0.resolved_transaction_type_details.source,default,default,default,default,default,default,default,default,default,default,default,default,default
transactions.0.resolved_transaction_type_details.type,FlexibleRepoCollateralTransfer,BondCoupon,BondCoupon,BondCoupon,BondCoupon,BondCoupon,BondCoupon,FlexibleRepoCashTransfer,FlexibleRepoCollateralTransfer,FlexibleRepoInterestPayment,Maturity,BondCoupon,BondCoupon
transactions.0.version.effective_from,2025-01-02 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-04-28 00:00:00+00:00,2025-05-28 00:00:00+00:00
transactions.0.version.as_at_date,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00,2026-06-10 11:46:01.891917+00:00
transactions.0.version.entity_unique_id,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000
eligible_balance,1.00,4.00,1.00,4.00,1.00,4.00,1.00,1.00,1.00,1.00,1.00,3.00,3.00

Seller-Term

,0,1,2,3,4,5,6,7,8,9,10,11,12
portfolio_id.scope,FBNTutorials,FBNTutorials,FBNTutorials,FBNTutorials,FBNTutorials,FBNTutorials,FBNTutorials,FBNTutorials,FBNTutorials,FBNTutorials,FBNTutorials,FBNTutorials,FBNTutorials
portfolio_id.code,FlexRepo-Seller-Term,FlexRepo-Seller-Term,FlexRepo-Seller-Term,FlexRepo-Seller-Term,FlexRepo-Seller-Term,FlexRepo-Seller-Term,FlexRepo-Seller-Term,FlexRepo-Seller-Term,FlexRepo-Seller-Term,FlexRepo-Seller-Term,FlexRepo-Seller-Term,FlexRepo-Seller-Term,FlexRepo-Seller-Term
holding_id,81088537,81088536,81088537,81088536,81088537,81088536,81088537,81088537,81088537,81088537,81088537,81088536,81088536
lusid_instrument_id,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1Q,LUID_00003H1Q,LUID_00003H1Q,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1O
instrument_scope,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo
instrument_type,FlexibleRepo,Bond,FlexibleRepo,Bond,FlexibleRepo,Bond,FlexibleRepo,FlexibleRepo,FlexibleRepo,FlexibleRepo,FlexibleRepo,Bond,Bond
instrument_event_type,FlexibleRepoCollateralEvent,BondCouponEvent,BondCouponEvent,BondCouponEvent,BondCouponEvent,BondCouponEvent,BondCouponEvent,FlexibleRepoCashFlowEvent,FlexibleRepoCollateralEvent,FlexibleRepoInterestPaymentEvent,MaturityEvent,BondCouponEvent,BondCouponEvent
instrument_event_id,LUID_00003H1Q_FlexibleRepoCollateralEvent_2025...,LUID_00003H1O_BondCouponEvent_20250128,LUID_00003H1O_BondCouponEvent_20250128-Manufac...,LUID_00003H1O_BondCouponEvent_20250228,LUID_00003H1O_BondCouponEvent_20250228-Manufac...,LUID_00003H1O_BondCouponEvent_20250328,LUID_00003H1O_BondCouponEvent_20250328-Manufac...,LUID_00003H1Q_FlexibleRepoCashFlowEvent_2025-0...,LUID_00003H1Q_FlexibleRepoCollateralEvent_2025...,LUID_00003H1Q_FlexibleRepoInterestPaymentEvent...,LUID_00003H1Q_MaturityEvent_20250331,LUID_00003H1O_BondCouponEvent_20250428,LUID_00003H1O_BondCouponEvent_20250528
generated_event.instrument_event_id,LUID_00003H1Q_FlexibleRepoCollateralEvent_2025...,LUID_00003H1O_BondCouponEvent_20250128,LUID_00003H1O_BondCouponEvent_20250128-Manufac...,LUID_00003H1O_BondCouponEvent_20250228,LUID_00003H1O_BondCouponEvent_20250228-Manufac...,LUID_00003H1O_BondCouponEvent_20250328,LUID_00003H1O_BondCouponEvent_20250328-Manufac...,LUID_00003H1Q_FlexibleRepoCashFlowEvent_2025-0...,LUID_00003H1Q_FlexibleRepoCollateralEvent_2025...,LUID_00003H1Q_FlexibleRepoInterestPaymentEvent...,LUID_00003H1Q_MaturityEvent_20250331,LUID_00003H1O_BondCouponEvent_20250428,LUID_00003H1O_BondCouponEvent_20250528
generated_event.instrument_identifiers.Instrument/default/ClientInternal,Seller-TermFlexRepo,BondCollateral,Seller-TermFlexRepo,BondCollateral,Seller-TermFlexRepo,BondCollateral,Seller-TermFlexRepo,Seller-TermFlexRepo,Seller-TermFlexRepo,Seller-TermFlexRepo,Seller-TermFlexRepo,BondCollateral,BondCollateral
generated_event.lusid_instrument_id,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1Q,LUID_00003H1Q,LUID_00003H1Q,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1O
generated_event.instrument_scope,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo
generated_event.description,Queried External Instrument Event of Type Flex...,Queried External Instrument Event of Type Bond...,Queried External Instrument Event of Type Bond...,Queried External Instrument Event of Type Bond...,Queried External Instrument Event of Type Bond...,Queried External Instrument Event of Type Bond...,Queried External Instrument Event of Type Bond...,Queried External Instrument Event of Type Flex...,Queried External Instrument Event of Type Flex...,Queried External Instrument Event of Type Flex...,Queried External Instrument Event of Type Matu...,Queried External Instrument Event of Type Bond...,Queried External Instrument Event of Type Bond...
generated_event.event_date_range.start,2025-01-02 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-04-28 00:00:00+00:00,2025-05-28 00:00:00+00:00
generated_event.event_date_range.end,2025-01-02 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-04-28 00:00:00+00:00,2025-05-28 00:00:00+00:00
generated_event.completeness,Complete,Complete,Complete,Complete,Complete,Complete,Complete,Complete,Complete,Complete,Complete,Complete,Complete
generated_event.instrument_event.instrument_event_type,FlexibleRepoCollateralEvent,BondCouponEvent,BondCouponEvent,BondCouponEvent,BondCouponEvent,BondCouponEvent,BondCouponEvent,FlexibleRepoCashFlowEvent,FlexibleRepoCollateralEvent,FlexibleRepoInterestPaymentEvent,MaturityEvent,BondCouponEvent,BondCouponEvent
generated_event.properties,[],[],[],[],[],[],[],[],[],[],[],[],[]
generated_event.sequence_number,20,20,20,20,20,20,20,20,20,30,1000,20,20
generated_event.participation_type,Mandatory,Mandatory,Mandatory,Mandatory,Mandatory,Mandatory,Mandatory,Mandatory,Mandatory,Mandatory,Mandatory,Mandatory,Mandatory
generated_event.group_code,Tier2,Tier3,Tier3,Tier3,Tier3,Tier3,Tier3,Tier2,Tier2,Tier2,Tier3,Tier3,Tier3
transactions.0.transaction_id,LUID_00003H1Q_FlexibleRepoCollateralEvent_2025...,LUID_00003H1O_BondCouponEvent_20250128-81088536,LUID_00003H1O_BondCouponEvent_20250128-Manufac...,LUID_00003H1O_BondCouponEvent_20250228-81088536,LUID_00003H1O_BondCouponEvent_20250228-Manufac...,LUID_00003H1O_BondCouponEvent_20250328-81088536,LUID_00003H1O_BondCouponEvent_20250328-Manufac...,LUID_00003H1Q_FlexibleRepoCashFlowEvent_2025-0...,LUID_00003H1Q_FlexibleRepoCollateralEvent_2025...,LUID_00003H1Q_FlexibleRepoInterestPaymentEvent...,LUID_00003H1Q_MaturityEvent_20250331-81088537,LUID_00003H1O_BondCouponEvent_20250428-81088536,LUID_00003H1O_BondCouponEvent_20250528-81088536
transactions.0.type,FlexibleRepoCollateralTransfer,BondCoupon,BondCoupon,BondCoupon,BondCoupon,BondCoupon,BondCoupon,FlexibleRepoCashTransfer,FlexibleRepoCollateralTransfer,FlexibleRepoInterestPayment,Maturity,BondCoupon,BondCoupon
transactions.0.instrument_identifiers.Instrument/default/LusidInstrumentId,LUID_00003H1O,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1O
transactions.0.instrument_scope,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo
transactions.0.instrument_uid,LUID_00003H1O,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1Q,LUID_00003H1Q,LUID_00003H1O,LUID_00003H1O
transactions.0.transaction_date,2025-01-02 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-04-28 00:00:00+00:00,2025-05-28 00:00:00+00:00
transactions.0.settlement_date,2025-01-02 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-04-28 00:00:00+00:00,2025-05-28 00:00:00+00:00
transactions.0.units,-1.00,2.00,1.00,2.00,1.00,2.00,1.00,1.00,1.00,1.00,1.00,3.00,3.00
transactions.0.transaction_price.price,0.00,20.83,20.83,20.83,20.83,20.83,20.83,"-1,000,000.00",0.00,"-12,054.79",0.00,20.83,20.83
transactions.0.transaction_price.type,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,CashFlowPerUnit,Price,CashFlowPerUnit,CashFlowPerUnit
transactions.0.total_consideration.amount,0.00,41.67,20.83,41.67,20.83,41.67,20.83,"-1,000,000.00",0.00,"-12,054.79",0.00,62.50,62.50
transactions.0.total_consideration.currency,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP
transactions.0.exchange_rate,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
transactions.0.transaction_currency,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP,GBP
transactions.0.properties.Transaction/SHKs/BondCollateralCoupons.key,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons,Transaction/SHKs/BondCollateralCoupons
transactions.0.properties.Transaction/SHKs/BondCollateralCoupons.value.label_value,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>,<Not Classified>
transactions.0.properties.Transaction/system/OverrideOfInstrumentEvent.key,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent,Transaction/system/OverrideOfInstrumentEvent
transactions.0.properties.Transaction/system/OverrideOfInstrumentEvent.value.label_value,LUID_00003H1Q_FlexibleRepoCollateralEvent_2025...,LUID_00003H1O_BondCouponEvent_20250128,LUID_00003H1O_BondCouponEvent_20250128-Manufac...,LUID_00003H1O_BondCouponEvent_20250228,LUID_00003H1O_BondCouponEvent_20250228-Manufac...,LUID_00003H1O_BondCouponEvent_20250328,LUID_00003H1O_BondCouponEvent_20250328-Manufac...,LUID_00003H1Q_FlexibleRepoCashFlowEvent_2025-0...,LUID_00003H1Q_FlexibleRepoCollateralEvent_2025...,LUID_00003H1Q_FlexibleRepoInterestPaymentEvent...,LUID_00003H1Q_MaturityEvent_20250331,LUID_00003H1O_BondCouponEvent_20250428,LUID_00003H1O_BondCouponEvent_20250528
transactions.0.source,default,default,default,default,default,default,default,default,default,default,default,default,default
transactions.0.entry_date_time,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00
transactions.0.transaction_status,Active,Active,Active,Active,Active,Active,Active,Active,Active,Active,Active,Active,Active
transactions.0.transaction_group_id,LUID_00003H1Q_FlexibleRepoCollateralEvent_2025...,LUID_00003H1O_BondCouponEvent_20250128,LUID_00003H1O_BondCouponEvent_20250128-Manufac...,LUID_00003H1O_BondCouponEvent_20250228,LUID_00003H1O_BondCouponEvent_20250228-Manufac...,LUID_00003H1O_BondCouponEvent_20250328,LUID_00003H1O_BondCouponEvent_20250328-Manufac...,LUID_00003H1Q_FlexibleRepoCashFlowEvent_2025-0...,LUID_00003H1Q_FlexibleRepoCollateralEvent_2025...,LUID_00003H1Q_FlexibleRepoInterestPaymentEvent...,LUID_00003H1Q_MaturityEvent_20250331,LUID_00003H1O_BondCouponEvent_20250428,LUID_00003H1O_BondCouponEvent_20250528
transactions.0.resolved_transaction_type_details.scope,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo,FBNTutorialsFlexRepo
transactions.0.resolved_transaction_type_details.source,default,default,default,default,default,default,default,default,default,default,default,default,default
transactions.0.resolved_transaction_type_details.type,FlexibleRepoCollateralTransfer,BondCoupon,BondCoupon,BondCoupon,BondCoupon,BondCoupon,BondCoupon,FlexibleRepoCashTransfer,FlexibleRepoCollateralTransfer,FlexibleRepoInterestPayment,Maturity,BondCoupon,BondCoupon
transactions.0.version.effective_from,2025-01-02 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-01-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-02-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-28 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-03-31 00:00:00+00:00,2025-04-28 00:00:00+00:00,2025-05-28 00:00:00+00:00
transactions.0.version.as_at_date,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00,2026-06-10 11:46:03.149938+00:00
transactions.0.version.entity_unique_id,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000,00000000-0000-0000-0000-000000000000
eligible_balance,1.00,2.00,1.00,2.00,1.00,2.00,1.00,1.00,1.00,1.00,1.00,3.00,3.00

## Load manual closure events as corporate actions

`FlexibleRepoFullClosureEvent` and `FlexibleRepoPartialClosureEvent` events are not automatically emitted by LUSID and so must be loaded into a portfolio's corporate action source manually. See https://support.lusid.com/docs/handling-instrument-events-for-repurchase-agreements#appendix-triggering-a-partial-or-full-closure.

### Load `FlexibleRepoFullClosureEvent`

To demonstrate, uncomment this and create the `OpenRepo` instruments and portfolios, above.

In [47]:
# def full_closure_open_repo(luid, date):
    
#     ca_request = lm.UpsertInstrumentEventRequest(
#         # A corporate action event must have a unique identifier within its corporate action source
#         instrument_event_id = f"{luid}-{date}",
#         instrument_identifiers = {f"Instrument/default/LusidInstrumentId": luid },
#         description = f"{luid}-{date}",
#         instrument_event = lm.FlexibleRepoFullClosureEvent(
#             instrument_event_type = "FlexibleRepoFullClosureEvent",
#             entitlement_date = to_date(date),
#             settlement_date = to_date(date)
#         )
#     )
    
#     # Upsert corporate actions to LUSID as instrument events
#     try:
#         ca_response = corporate_action_sources_api.upsert_instrument_events(
#             scope = module_scope,
#             code = module_code,
#             upsert_instrument_event_request = [ca_request]
#         )
#         print(ca_response.failed) if ca_response.failed else print("Success")
#     except lu.ApiException as e:
#         print(e)

In [48]:
# full_closure_open_repo(luid_dict["Buyer-OpenFlexRepo"], "2025-01-18")

In [49]:
# for port in ports:
#     print(f"\n{port}")
#     get_portfolio_holdings(port, "2025-01-17 00:00:00") # Day before
#     get_portfolio_holdings(port, "2025-01-18 00:00:00") # Full closure date
#     get_output_transactions(port, "2025-01-01", "2025-07-30")
#     query_instr_events(port)